### ISSUE TITLE
Content Creator & Megaphone for the Stacks ecosystem.

### ISSUE THREAD

**Issue by JakeBlockchain** [stacksgov/residence-program#1]
**What's your name/your team's name?**
Jacob Brown aka JakeBlockchain

**Best email on which to contact you?**
jakeblockchain@protonmail.com

**Personal Statement**
The plan is to have interesting discussions, with interesting people creating dope stuff in the Stacks community.,
Through the myriad of social platforms, I want to expand the total number of people who follow Stacks by interviewing interesting people in the community, and shine a spotlight on them with longer form deep dives (Podcast form and YouTube) and quick, concise, cut-down clips that engage and bring in new (ETH) users to the light side.
The hard and fun part for me is taking a complex topic and making it easy to understand for the people that haven't gone down the crypto rabbit hole yet. That's where I come in.

**End Product**
The end result will be an array of content on all the social platforms (YouTube, All major podcast platforms, Twitter, TikTok, LinkedIn, & Instagram for sure.)
I will have weekly podcasts and clips go live. 
Ranging from an hour in length to less then a minute. Each type of content will serve a slightly different person in their journey learning and understanding Stacks.
In 6 months, I'd expect around 125+ pieces of content to go up. 

**Roadmap** 
- <Milestone 1> Release the first 25 pieces of content (5 weeks)
- <Milestone 2>  Create a set of explainer videos for all the common Stacks mechanisms (12 weeks)
- <Milestone 3>  Interview all 25 teams in the first Stacks Accelerator cohort (25 Weeks)
These are rough estimates. Would love to explore milestones more in-depth with the foundation.

**Appendix**
[Attach any supplemental materials such as previous work/accolades, notes, diagrams, preliminary research, or community interactions that could support your application.]
Patrick Stanley YouTube Interview: https://youtu.be/2y0KEofK1A4**
Built on Bitcoin Podcast page: https://podpage.com/built-on-bitcoin
CEO of Layer interview:
https://youtu.be/IiFwVKWzAkM
Different styles of content: https://www.dropbox.com/s/p6qoz5g0nosmny9/Clarity%20Universe.mp4?dl=0

**Comment by jennymith** [comment]
Hey Jake, thanks for submitting an application (one of the very first!) to become a Stacks Resident. The Foundation team is reviewing your application in more depth and will be getting back to you about next steps soon.
