### ISSUE TITLE
Tycho Onnasch as an Entrepreneur-in-Residence to boost DeFi on STX 

### ISSUE THREAD

**Issue by louiseivan** [stacksgov/residence-program#11]
**Whom are you nominating to become a Stacks Resident?**
**Tycho Klaus Otto Onnasch**

**Are they already part of the Stacks community?**
**YES**

**Explain in 150 words or less why you are nominating this individual.**
DeFi on Bitcoin is an incredibly strong narrative. When new investors first allocate to crypto by buying Bitcoin, they are often surprised to learn that yields only exist on other chains. They have a healthy skepticism towards these chains. STX suffers from this skepticism as well. As a result, STX becomes the best contender in the DeFi Space that no one knows about. 

**Explain in 150 words or less why their work is relevant or beneficial to Stacks.**
Yet, STX has significant intellectual capital to counter this skepticism. The SEC-qualified token offering, an excellent track record of shipping technology, and the strong community all contribute to a compelling thesis that STX has the highest potential to scale Bitcoin’s hash power out of any protocol. The momentum for cementing this narrative is now as we’re moving through a sustained bull market and work on exchange listings, bridges and the first apps is coming to fruition.

**Explain in 150 words or less what you think they can contribute as a Resident.**

The goal of this residency is to nail the pitch for Stacks to own the narrative of DeFi on Bitcoin with the various Stakeholders of the ecosystem.

The completion of the goal is qualified by the following deliverables:

1. Establish at least 1 significant partnership with TradFi to boost liquidity on STX (i.e. Greyscale STX trust)

2. Empower at least 1 national blockchain initiative through STX technology (El Salvador was the first country to adopt Bitcoin but signed Algorand to develop the government’s blockchain infrastructure - this could’ve been an easy win for STX)

3. Expand the network of liquidity providers for STX DeFi protocols

4. Onboard at least 1 EVM DEX to integrate STX native chain

5. Build DeFi on Bitcoin resources suite to convey effectively what’s possible today by building on STX

**Appendix**
Tycho first learned about Bitcoin when he was 14 years old and developed a keen interest in finance shortly after. He went on to study History & Politics at the University of Oxford where he focussed on economic and financial history from the Medici to crypto. During his time at Oxford, he was elected to the governing body of the Oxford Union Debating Society where he organized debates about topics on the intersection of technology, finance, and politics with world leaders. These exchanges made Tycho somewhat skeptical about the world of finance and he decided to build a software company instead. 

He built [Deedmob](https://www.deedmob.com/), a SaaS company to help organizations boost civic engagement. He set out on a VC-backed plan to build a billion-dollar company by making it easy for everyone to volunteer across the globe. The plan didn't work so he turned Deedmob into a profitable SaaS company instead to ensure lasting impact. Since then he's been helping the team build in the Stacks ecosystem through mentorship at the Accelerator and developed a deep interest in Defi. Tycho also moderates discussions at various European banking and finance conferences and sits on the Amsterdam Economic Board.

**Comment by stackswap** [comment]
I would also support Tycho as EIR. Stackswap team and Tycho had multiple discussions on how to make Stacks Defi ecosystem flourish over many months. Tycho not only has a deep understanding of Defi, but also is full of practical ideas that could be immensely beneficial for both the short and long term growth of Stacks Defi.

**Comment by ChienteH** [comment]
I endorse Tycho's nomination. Tycho has been following ALEX since day one and has consistently raised thoughtful questions and provided insight. He's a deep and critical thinker with a natural curiosity for DeFi. As a resident he would be a great asset to the Stacks and DeFi.

**Comment by tycho1212** [comment]
Hi everybody! Thanks for your support - this means a lot ❤️ 

I'm going to focus on building something in the DeFi space on Stacks instead. I think this is a better fit for me considering my experience and what I enjoy doing most. I also think I could have a bigger impact on the Stacks ecosystem in this way.

@jennymith unfortunately I won't be able to accept the nomination

See you soon! It's time to build 💪

**Comment by jennymith** [comment]
Thanks for considering @tycho1212 and good luck with your DeFi project!
