### ISSUE TITLE
MineNFTcoins or NFT subnet Collection :package: 

### ISSUE THREAD

**Issue by Rapha-btc** [stacksgov/residence-program#13]
**What's your name/your team's name?**

Hodlstx.btc
Friedger
Rapha Rodriguez (rapha.btc)

**Best email on which to contact you?**
rapha@fontainebleau-management.com
contact@minenftcoin.com 

**Personal Statement**
[Explain in 150 words or less the kind of work you'd like to do and why you think it could advance the ecosystem.]
- Exploring MineNFTcoin idea in collaboration with Friedger and James.

- Running 250 more miles in 5 weeks, while having the community to elect the specimen of Collection 2 to be minted as NFT at the end of my run (for a total of 350, already 100 miles ran and fundraising for Divya completed -> see here: https://www.fontainebleau-management.com/2021/10/11/fundraising-for-divya-btc-completed/)

- If Friedger is not against it, using Collection 2 to fix limit supply of Collection 1 (7 bitcoin days), and owners of collection 1 NFTs will have the exclusivity to mine NFTs of Collection 2 for a fixed period of time after which minting will become open to all

**End Product**
[Describe in 150 words or less the what you plan to contribute to the community by the end of your residency, e.g. a whitepaper or a series of developer tools.]

- Resolving the issue of artists having minted their collections without a fixed supply enforced by code
- Creating a novel protocol called Mined NFT that would allow any NFT owner to "mine" their NFT into an official Museum Community Collection -> a completely open source protocol where mined NFTs are fractionalized along with a fungible token awarded to the winner of mining block
- If applicable, creating the rules governing a standard Subnet representing an official museum collection ( if subnet makes sense / or app chain does...) -> such as how to enter/exit the collection, trading of the official NFTs, royalty mechanism, stacking mechanism if applicable

**Roadmap**
[Break your project down into a simple list of milestones and include the *approximate* dates by when you plan to complete them.]
- 5 weeks: having 7 NFT candidates elected by the community + 350 miles ran + 5 video with Emmanuel Anthony Omachoko My French Community student from Nigeria who recently graduated from the Jedi program and was awarded a grant by his university to go and study in France
- TBD weeks: smart contracts providing the solution to artists to fix their limit supply in hindsight using a collection 2 
- TBD weeks: document describing the mechanism of a Community Collection (subnet/appchain/PoX/DAO)

**Appendix**
[Attach any supplemental materials such as previous work/accolades, notes, diagrams, preliminary research, or community interactions that could support your application.]

https://twitter.com/RaphaelRSierra/status/1447952063862906884
https://www.fontainebleau-management.com/2021/10/11/fundraising-for-divya-btc-completed/
https://twitter.com/RaphaelRSierra/status/1447167853279465476

![image](https://user-images.githubusercontent.com/6700158/137011835-e096b529-efa5-469a-89bb-cd1a95ac0786.png)

**Comment by Rapha-btc** [comment]
Hello Jenny, Thank you for your time and prompt response. 

I initially wrote this short draft to get our conversation started. It needs to be re-framed solely on the idea of the museum of NFTs. Therefore the 1rst milestone is no longer part of the scope (answers your question?).

Moreover, I have given full leadership of the project to James, although I am happy to explore the idea of contributing in one way or another. It is an exciting idea IMHO! 

I know Friedger, Dan and Alexander have discussed with James and myself about this. Next, James wanted to approach protocol designer persons or other resources to further validate the definition of the project.

Are you against helping with having someone at protocol design get a look at this idea? A 15 minute call with James and other contributors could make a difference.

Thanks for your time and diligence.

**Comment by jennymith** [comment]
Hi @Rapha-btc mind tagging James here? We just want to get a clearer sense of who/what team would be officially leading this project. Is this something that @dantrevino and the Boom team would consider taking on in their residency?

**Comment by Rapha-btc** [comment]
Sure, I'll transfer your message to them and on discord!
