### ISSUE TITLE
Ileana Malacrino as an NFT-in-Residence to grow the Creator Economy on STX 

### ISSUE THREAD

**Issue by louiseivan** [stacksgov/residence-program#15]
**Whom are you nominating to become a Stacks Resident?**
Ileana Malacrino

**Are they already part of the Stacks community?**
Yes

**Explain in 150 words or less why you are nominating this individual.**
As most YouTubers would say, _" Bitcoin NFTs are getting hot right now; while the community is tightknit and small, they are growing very, very fast."_  

We can't deny the momentum as our overall NFT trading volume crossed 4m$ in three weeks. What we need right now is to drive it further by bringing our Bitcoin-powered NFTs to the mainstream. This is a straightforward nomination with the overall goal of onboarding more creators and brands to the Stacks ecosystem. 

**Explain in 150 words or less why their work is relevant or beneficial to Stacks.**
Several brands jumped into the minting frenzy, including — Gucci, Louis Vuitton, Budweiser, Visa, McDo, Snoop Dog, and many more. The question is here, why not on Stacks? Bitcoin NFTs seems like the best option. In short, there's a gap and we need to bridge it. 

We have a great proposition on how we recycle PoW and mint NFTs without increasing their environmental impact; all we need is a dedicated Stacker to focus solely on the creator economy. Ileana, who's been working with big brands such as Budweiser, Foreo, Dubai, Dr. Brandt, and more could help bridge this gap. With her expertise in the creators' space for years, She can handheld creators and brands to the Stacks ecosystem.

**Explain in 150 words or less what you think they can contribute as a Resident.**

The goal of this residency is to forefront Stacks Bitcoin NFTs to the mainstream. Some of the key deliverables could be 👇🏽 

1. Bitcoin NFT Resources and Kit for Creators and Brand
- How to onboard and incentivize creators and brands to use Stacks
- How to launch Social tokens and the benefits they can bring to creators
2. Creator and brands onboarding and relationship building
3. Build a long term strategy for NFTs and social tokens on Stacks
4. Onboard at least 1 big brand to Stacks
5. Onboard at least 3 big artists to Stacks

**Appendix**
Ileana is currently the [Head of Creative at IMF.](https://www.linkedin.com/in/ileanamalacrino/?originalSubdomain=nl) She has a demonstrated history of working in the influencer marketing and advertising industry.

**Comment by GAD2511** [comment]
This is the genius proposal that will definitely bring Stacks to the mainstream. And the choice of Ileana Malacrino is all the way the best one to go.
Indeed Bitcoin NFT is growing very fast and we are seeing many creators interested in Stacks ecosystem for creations. I think Stacks has to implement creator economy and features that will help creators to benefit from their creations in the long term. For example tools that can help artists benefit from secondary markets (at least 5x or even lifetime % from secondary market) to incentivize them create high quality content that can be accepted by mainstream.
Personally I bet on Ileana for her XP and  vision

**Comment by cristinacanale** [comment]
I would like to back this nomination - I've worked with Ileana for two years on global influencer campaigns and I have seen first hand the excellent results she has achieved. Her strength is within no doubt the ability to build strong relationship with the creators, while helping brands in achieving their goals.  Ileana is ambitious, persistent and incredibly driven - with the ability to introduce a network of brands and creators to the Stacks ecosystem.

Cristina Canale, Brand PR manager at Just Eat Takeaway

**Comment by tycho1212** [comment]
Good idea! I think we need all the resources on this we can get.

Ileana has worked with some of the teams I mentored as part of the Stacks Accelerator. I would definitely recommend her to anyone and endorse her for the Residency. She's a hustler! We'd be lucky to have her work full time on this

Rooting for this nomination to go through 🤞

**Comment by sannebogers** [comment]
I fully endorse this nomination! Having worked with Ileana for a decent amount of time, I know she has vision for both brands and creators. Being creative, yet analytical, she knows how to build strategy for the business side whilst keeping a close eye on appealing content and current trends. In my opinion the perfect person with relevant experience to fill this gap.

Ileana is incredibly dedicated when it comes to pushing for top results and won’t stop until she or anyone around her is fully satisfied. I would wish anyone a valuable member like her in their circle. 

Sanne Bogers, Head of Brand at Yummygums vitamin gummies

**Comment by alicjann** [comment]
Definitely confirming the nomination of Ileana! I've had a pleasure to work with Ileana in the past year on multiple of NFT projects and I am honestly amazed by her drive and knowledge. I've been able to learn a lot from her and she has a power to bring her great ideas into actions. Besides that we've been working together for many years on multiple influencer marketing campaigns for well established brands. I don't know second person who is as dedicated to what she's doing as her.

I believe Ileana is a great candidate for the Stacks Resident and she will be able to bring her valuable experience that the community will benefit from.

**Comment by jennymith** [comment]
Hi @louiseivan, we'd love to get to know Ileana more! Are you able to tag her here or share her email address?
