### ISSUE TITLE
Residency for Ocelo Team 

### ISSUE THREAD

**Issue by diopitis** [stacksgov/residence-program#18]
**What's your name/your team's name?**
The Ocelo team, comprised of Dioptis/Invidia

**Best email on which to contact you?**
invidia@ocelo.io
diopitis@ocelo.io

**Personal Statement**
[Explain in 150 words or less the kind of work you'd like to do and why you think it could advance the ecosystem.]

One of the biggest issues in web3 is finding individuals to help with developing new technologies. Ocelo is trying to bridge the gap between those with ideas and those able to build. Ocelo makes central parties redundant by utilizing clarity smart contracts for escrow payments between dreamers and builders. We also will have a jury system for handling disputes if they arise between the two parties. This will all be handled by a smart contract and jurors will be compensated by participating. 

**End Product**
[Describe in 150 words or less the what you plan to contribute to the community by the end of your residency, e.g. a whitepaper or a series of developer tools.]

By the end of our residency we will have a full fledged platform where people can find work or be hired using escrow payments with Stacks and other SIP-010 tokens. Users can post jobs, view workers profiles, portfolios, message them, invite them to jobs, and leave reviews. We will have a smart contract which handles the escrow between users as well as settle decisions from the jury on disputes.

**Roadmap**
[Break your project down into a simple list of milestones and include the *approximate* dates by when you plan to complete them.]
- <Milestone 1>
Clarity Smart Contract for holding payments, dispute handling, and hashing of job contract data
-<Milestone 2>
Unit Testing of the contract and deploying on Testnet for early testing
- <Milestone 3>
Research into what technologies we should use for our backend. to remain as decentralized as possible(messaging, file storage etc.)  we need to further research encryption to make sure all offchain data such as messaging remains as secure as possible.  
- <Milestone 4>
Development of our application backend incorporating everything in milestone 3.
-<Milestone 5>
UI/UX design for our platform 
-<Milestone 6>
Developing a fully functional web app to handle stacks authentication, contract calls, job postings, user profiles, and messaging.
- ...

**Appendix**
[Attach any supplemental materials such as previous work/accolades, notes, diagrams, preliminary research, or community interactions that could support your application.]

The Ocelo team is comprised of Dioptis and Invidia. We are both developers who have been very active in the Stacks ecosystem. Some of our previous work include the [Miami Coin UI](https://minemiamicoin.com/), which was the UI used to initialize mining and for stacking MiamiCoin. We also built MIamiPool which is a completely decentralized [MIA mining pool](https://mine.miami/) . The contract we created for this is [here.](https://explorer.stacks.co/txid/SP343J7DNE122AVCSC4HEK4MF871PW470ZSXJ5K66.miamipool-v1?chain=mainnet) We are currently running the [Syvita mining pool](https://syvitamining.com/) for New York coin and have launched our new  mining smart contract found [here](https://explorer.stacks.co/txid/0xd650e0e935a3b7325046acb3d1406db78b9ced4153eadd5e88ee52d042b62044?chain=mainnet).

![ocelo-flow-chart](https://user-images.githubusercontent.com/54492027/146285303-a0848d82-0de2-4e3a-97f8-81044e995cdf.png)

**Comment by BowTiedMooneeb** [comment]
This looks like a great application solving a real world problem that I believe Diopitis & Invidia have direct experience with. Matching entrepreneurs with developers in a trustless fashion has the potential to accelerate the growth of the Stacks ecosystem.

I can personally vouch for the skill & integrity of Diopitis & Invidia, as we have worked together on Syvita's mining operations. They have developed a consistent track record of high quality execution, always responsive and respectful, and overall a pleasure to work with. They maintain the highest level of personal responsibility, ethics, and responsiveness. 

This team would make a great addition to the Stacks resident community.

**Comment by ChienteH** [comment]
I support this project. Talent is the scarce resource. ALEX constantly needs good developers. I believe Stacks eco system needs a decentralized talent agent which is Ocelo.

**Comment by Clinamenic** [comment]
This seems like a solid project. Ambitious, but also clearly laid out into manageable steps. 

The jury be comprised of volunteers, or will jury members be chosen at random? I like how they are incentivized via compensation, but I suspect a volunteer jury may attract friends/associates of the developer or client. Maybe there is a way for jurors to volunteer without knowing the developer or client? Or maybe jurors can be chosen at random, then given a choice as to whether or not they want to participate?

**Comment by JakeBlockchain** [comment]
The clear scope of this feels more tailored for a grant.

**Comment by SyInvidia** [comment]
> The clear scope of this feels more tailored for a grant.

We originally applied for a grant! But because of how big the project is, the foundation recommended that we apply for a residency instead of a grant

**Comment by SyInvidia** [comment]
> This seems like a solid project. Ambitious, but also clearly laid out into manageable steps.
> 
> Will the jury be comprised of volunteers, or will jury members be chosen at random? I like how they are incentivized via compensation, but I suspect a volunteer jury may attract friends/associates of the developer or client. Maybe there is a way for jurors to volunteer without knowing the developer or client? Or maybe jurors can be chosen at random, then given a choice as to whether or not they want to participate?

To begin with, users will just be randomly selected as jurors. As the platform grows, we may only choose those who are in an active escrow, or we may develop a reputation system to determine the jurors. Users will have the ability to opt in or out of being a juror.

**Comment by 314159265359879** [comment]
> > The clear scope of this feels more tailored for a grant.
> 
> We originally applied for a grant! But because of how big the project is, the foundation recommended that we apply for a residency instead of a grant

Excellent idea! I think this is a valuable project for Stacks, a platform like this can instill talent development and match parties.

**Comment by BryanG1** [comment]
Voicing full support for Invidia & Dio in the residency program.

**Comment by rodrigo-moonray** [comment]
Moonray supports this project as well, we spoke with them about this and it sounds like a service that could be very useful

**Comment by philipdesmedt** [comment]
We'd love to see this project come to fruition. From the Arkadiko side, I see two benefits:

1. USDA usage as a means of payment
2. When Ocelo hits mainnet, we will use this to pay some of our core contributors in DIKO or USDA

Let's go!

**Comment by falkonprods** [comment]
As a current resident and Stacks builder, I can say we absolutely need this in the Stacks ecosystem, and Dioiptis and Invidia are invaluable members of the community who I would totally trust to build it right...
