### ISSUE TITLE
Media as a yeild producing asset

### ISSUE THREAD

**Issue by christianblaze** [stacksgov/residence-program#19]
**What's your name/your team's name?**
- Christian Blaze / Crystal Insight New Media

**Best email on which to contact you?**
- info@crystalinsight.com

**Personal Statement**
- Traditional media (Film, TV, etc) has been reduced down to a vehicle by which advertisers can sell consumers on their products and services, be it a soda company wanting to sell more drinks, or a government wanting to sell the public on specific policy.  Because of the traditional economic dynamics at play, art, and by proxy artists, take a back seat to the desires of the advertisers who, in essence, pay for the privilege of buying time within the minds of the audience. It's time for an alternative model: 
- I propose developing a type of NFT, on Stacks, that represents ownership over a piece of media (ie: video, music, etc). The NFT will generate a yield for those who hold it.  The media can be shared/delegated to others, and during the time they have "borrowed" the NFT, benefit from the yield the asset produces.

**End Product**
- The End Product would be a whitepaper, followed by the creation of a Prototype, using code written in Clarity.

**Roadmap**
[Break your project down into a simple list of milestones and include the *approximate* dates by when you plan to complete them.]

- Whitepaper - March 1st, 2022
- Prototype    - May 1st, 2022

**Appendix**
- I am the CEO of www.crystalinsight.com
- I have worked in the film industry for more than 20 years: https://www.imdb.com/find?q=christian+blaze&ref_=nv_sr_sm
-  I have followed Muneeb's work since the Namecoin days.
- Our company was one of the first miners to mine blocks when the Stacks V2 Mainnet went live.
- I have had some preliminary conversations about this idea with community members who have expressed interest in helping develop it further.

**Comment by jennymith** [comment]
Hey Christian, thanks for applying to be a Stacks Resident. The Foundation team is currently reviewing your application in more depth and will be getting back to you about next steps soon.

**Comment by christianblaze** [comment]
Sounds good.
Thanks for the update Jenny.

**Comment by will-at-stacks** [comment]
Hi @christianblaze -

Apologies in the delayed response.  I wanted to touch base with you and see if you are still interested in the Residency program.  If you are please let me know and we can schedule an initial interview with you.

Best,
Will

**Comment by christianblaze** [comment]
Yes, I am still interested... although after speaking with you, I think I'd
like to apply with the idea of developing the constitution for a
decentralized nation we spoke about, and build out from there... Would love
to talk more about it.

**Comment by christianblaze** [comment]
Here's the updated application: https://github.com/stacksgov/residence-program/issues/28
