### ISSUE TITLE
Technical Documentation Lead, Stacks Ecosystem

### ISSUE THREAD

**Issue by cuevasm** [stacksgov/residence-program#2]
As [discussed on the forum](https://forum.stacks.org/t/the-evolution-of-the-stacks-documentation-and-a-new-hiro-docs-site/12343), there's a clear need for someone to focus on Stacks-related technical documentation. 

**Proposed Title of Position**
Stacks Ecosystem Technical Documentation Lead (open to ideas here)

**Focus Areas/Scope of Work**
Two key parts are a) supporting the separation of Hiro docs from ecosystem docs and b) implementing a culture and process by which the community manages, contributes, and _maintains_ shared documentation going forward. 

**Responsibilities**
- Write, review, edit, & organize new and existing content
- Distill complex, technical topics and turn into easy to understand documentation
- Establish an efficient process for maintaining and updating documentation on an on-going basis
- Actively engage and involve community members to multiply documentation improvements
- ​Analyze, gather feedback, and research effectiveness and impact of documentation to identify opportunities for improvements

**Background & Skills**
- Experience with technical writing and editing, particularly with developer documentation
- ​Experience enforcing documentation standards, guidelines and driving best-practices
- Understanding of Markdown/MDX, Typescript, React/Next.Js
- Experience with development tools and practices(Git, GitHub and/or similar docs-as-code environment)
- Ability to learn new technologies quickly  

**Timeline**
I think this position works well in the context of an initial 3-month sprint to level-set docs and bring them up to speed, followed by a second 3-month sprint focused on process and incentives around making sure docs are well-taken care of by a larger group of regular contributors. A resident with the right skills could do both, or two people could tag team this in sequence. I do think the initial audit and setup is key to setting up the ongoing contributions, hence the 3 + 3 suggestion vs bringing in two residents at once on this.

**Interested? Apply here:** [https://stacks.org/stacks-resident](https://stacks.org/stacks-resident)

**Comment by DonnerKabab** [comment]
I'm interested.

**Comment by jennymith** [comment]
Hi all, if you're interested in this role, please apply here: [https://stacks.org/stacks-resident](https://stacks.org/stacks-resident). I've also updated the role description with the link.

**Comment by jhammond2012** [comment]
> Hi all, if you're interested in this role, please apply here: https://stacks.org/stacks-resident. I've also updated the role description with the link.

I have applied!

**Comment by cuevasm** [comment]
WOW, we got @jhammond2012?!

**Comment by jennymith** [comment]
For all community members interested in keeping up with @jhammond2012's residency, check out his plans for the next quarter and follow this thread for weekly updates from Jonathon himself:

### Scope of Work

**Background:**

As discussed on the forum, there's a clear need for someone to focus on Stacks-related technical documentation. In addition to the key focuses outlined, this role will also be responsible for delivering on the following goals over the next few months.

**Goals:**

- Write, review, edit, & organize new and existing content
- Distill complex, technical topics and turn them into easy to understand documentation
- Establish an efficient process for maintaining and updating documentation on an ongoing basis
- Actively engage and involve community members to multiply documentation improvements
- Analyze, gather feedback, and research effectiveness and impact of documentation to identify opportunities for improvements

**Timeline:**

- An initial 3-month sprint to level-set docs and bring the team up to speed, followed by a second 3-month sprint focused on process and incentives around making sure docs are well-taken care of by a larger group of regular contributors. I do think the initial audit and setup is key to setting up the ongoing contributions, hence the 3 + 3 suggestion vs bringing in two residents at once on this.

**Comment by jhammond2012** [comment]
Hi All!

A few announcements here that I am excited to share.

The one that is the furthest along is the translation. We have set up language detection and integration into [Crowdin](https://crowdin.com/). We are now working on setting up a reward system for community members who contribute to the translation efforts. Huge shoutout to Sleepi, Criadoperez.btc, and everyone else who has assisted me in this up to this point.

We also have been planning a 2 tiered interactive walkthrough system. The first mockups of this will be posted to this thread by Wednesday (2/9/22). I cannot describe the level of excitement I have for this. I will try to keep my explanation to a 30-second pitch. The idea here is to build out several interactive coding demonstrations to help new users get their feet wet in clarity. Imagine an in-browser IDE that walks a user through and allows them to create their first "Hello World!" contract right in the browser without them having to set up anything locally on their machine. Obviously, this can only get us so far and I don't see this being used for more complex tutorials. The idea and goal of this are to show the user that Clarity is not as scary as it may seem. 

I am also working with Kennny on building out a Next.JS style walkthrough to improve the onboarding experience of a new dev. Our vision is to first have the user complete these simple in-browser walkthroughs and then dive into this new experience. Our goal is to slowly ease them into the documentation and prevent them from getting lost in a web of confusion and intimidation. 

Lastly, I am speaking with [Scrimba](https://scrimba.com/scrim/czvKPPsw) on getting access as a creator to create some more in-depth tutorials with their platform. They offer an on-demand tutorial that plays as an in-person tutor session. The platform is really innovative and I feel that having some tutorials on there would go a long way.
