### ISSUE TITLE
Entrepreneur-in-Residence exploring Interoperability for NFTs

### ISSUE THREAD

**Issue by LayerTechnologies** [stacksgov/residence-program#21]
**What's your name/your team's name?**
Layer Technologies/heylayer.com

**Best email on which to contact you?**
gary@heylayer.com

Background
Heylayer is looking to provide brands with the tools they need to meet the heavy demands of managing the entire NFT industry. Our technology intends to make it easy for brands to deploy NFT campaigns at scale. 

Project Overview for 2022
While our goal is to have our base layer running on Stacks, we understand that leaning into interoperability is healthy for the future of NFTs and the Stacks ecosystem. Therefore, our project will focus on interoperability that makes sense for outside brands as they look to venture into web3. We plan to begin with Ethereum and Bitcoin. 

**Quarter 1 Month 1 - MetaMask Authentication**
Allow users to authenticate and sync a Metamask wallet. 
See update video: https://youtu.be/oJFQesor0Es
Status: IN PROGRESS

**Quarter 1 Month 2 - View Ethereum NFTs**
Allow users to see Ethereum NFTs alongside Stacks NFTs. 
See update video: https://youtu.be/zdHGfsl5Pi0
Status: IN PROGRESS

**Quarter 1 Month 3 - Buy NFTs with Bitcoin 1**
In collaboration with LNSwap, we plan to redesign the LNSwap widget allowing any marketplace that utilizes it to provide a much more refined experience to end-users.  

**Quarter 1 Month 4 - Buy NFTs with Bitcoin 2**
In coordination with LNSwap, work on more direct and seamless integration allowing collectors to buy NFTs with Bitcoin. 

ABOUT LAYER: https://drive.google.com/file/d/1oT24tO1w0nVRlBFG-NZyBiNAfTeottv_/view?usp=sharing

Thank you very much for this opportunity.

**Comment by will-at-stacks** [comment]
Hi @LayerTechnologies 

Apologies in the delayed response.  I wanted to touch base with you and see if you are still interested in the Residency program.  If you are please let me know and we can schedule an initial interview with you.

Best,
Will
