### ISSUE TITLE
Community Builder & Bitcoin Educator Providing Resources & Events for Women/NB to Learn, Connect, and Build on Bitcoin

### ISSUE THREAD

**Issue by satoshisarah** [stacksgov/residence-program#22]
**What's your name/your team's name?**
Sarah Satoshi (@satoshisarah)
**Best email on which to contact you?**
sarah@bitcoinladies.org
**Personal Statement**
[Explain in 150 words or less the kind of work you'd like to do and why you think it could advance the ecosystem.]

I am a Bitcoin educator and evangelist passionate about getting more people into the Bitcoin ecosystem (especially women), to help them build, learn, connect, and find purpose in Bitcoin and subsequently expand the community network. I've been working on free educational resources myself, but I want a landing page to help women/NB entering the Bitcoin ecosystem to have a resource site where they can find connections to things like education, grant opportunities(such as this one), job listings, mentorships, etc. Additionally, I'm working on planning events both in-person and online that appeal to more women, since it can be intimidating to enter a new (and highly technical) space that is heavily male-dominated.

I'm hoping to secure this grant to scale this project via comms development (I have a few interns), as well as fund myself to focus on this project rather than working for a company :) 

**End Product**
[Describe in 150 words or less the what you plan to contribute to the community by the end of your residency, e.g. a whitepaper or a series of developer tools.]

The end product would continue developing (see roadmap), but the main product would be a holistic published resource site along with continual expansion of events, resources development (like expanded jobs boards), and different social partnerships to introduce Bitcoin to existing cohorts of women (ie Ladies in Tech). 

**Roadmap**
[Break your project down into a simple list of milestones and include the *approximate* dates by when you plan to complete them.]

- Website published (by end of Feb)
- Setting up first webinar (March)
- Bitcoin 22 event w/ [redacted brands] potentially (beg of April)
- MIT Bitcoin Expo event (beg of May)
- Non-profit conversion (sometime in summer)
- LA Bitcoin event w/ Bitdevs LA (June)
- Summer internship programs (June)
- Mentorship kickstarter (August)
- University speaker event initiatives (August/September)
- continual development down the line; will update with concrete plans

**Appendix**
[Attach any supplemental materials such as previous work/accolades, notes, diagrams, preliminary research, or community interactions that could support your application.]

Bitcoin education: [b.tc/21days]
Community work @ : Des Femmes Magazine
Comms work @ : STXNFT
Stacks ecosystem contributions to accelerator 2021 cohort companies (like OAS)

**Comment by will-at-stacks** [comment]
Hi @satoshisarah 

Apologies in the delayed response.  I wanted to touch base with you and see if you are still interested in the Residency program.  If you are please let me know and we can schedule an initial interview with you.

Best,
Will

**Comment by satoshisarah** [comment]
Hey will!

Sorry for the late response, I had my github connected to this email and I've been trying to change it for a while, but github was always down when I tried to do it?!

I'm definitely still interested in the residency grant, would love to schedule an interview!

Sarah

------- Original Message -------

**Comment by will-at-stacks** [comment]
Hi @satoshisarah -

We would love to support your mission.  However, we think the best first step would be to position a first iteration of the published resource website.  If you are interested in this route I would love to chat further with you.  It could be really cool to build a team of lady bitcoiners to design and build it - Patricia obviously comes to mind.  I will leave those details to you though.  Please give this some thought and then lets chat.  I think once you have a deliverable of this magnitude built it will make your next steps (additional grants, residency, etc) that much more impactful.  Please email me when you want to talk further.

Best,
Will
