### ISSUE TITLE
Proposal for Clarity Education Residency

### ISSUE THREAD

**Issue by proiacm** [stacksgov/residence-program#24]
**What's your name/your team's name?**
Whitelabel Collaborative

**Best email on which to contact you?**
tim@varner.co, ciara@wlabel.co, aakanksha@wlabel.co

**Personal Statement**
In order to help the Stacks ecosystem grow, we believe it’s vitally important to continually equip developers to join the community. A training program is necessary to achieve this goal. We’re invested in the success of this program, making sure it improves cohort over cohort and is a great service to those developers entering the community. 

In order to accomplish this, we will maintain a small team of developers who share in the teaching workload, allowing us to achieve both redundancy and scale. Moreover, the team should be able to better accommodate logistical concerns, such as timezone differences. 

The effort will be initially led by CiaraMaria Proia, with the assistance and Aakanksha Mahajan. 

CiaraMaria Proia is a web3 developer who has been involved in the Stacks community since the summer of ’21 as one of the OG NFT collectors under the pseudonym [redacted].btc. Her enthusiasm for blockchain technology and the emerging Stacks ecosystem led her to begin learning Clarity and attend Clarity U cohort 2. She is currently involved in multiple projects throughout the ecosystem and is excited to work with the Stacks Foundation to bring more comprehensive education and resources to current and future Clarity devs.

Aakanksha Mahajan is a Full Stack Developer with 6+ years of industry experience in the design and implementation of web-based applications across diversified technology stacks and a range of programming languages. Her Web3 enthusiasm has led her to deeply explore blockchain development (beginning with solidity) and get familiar with the Stacks ecosystem. Aakanksha has tremendous skill at helping less experienced developers develop their knowledge base and a comfort level with new languages.

**End Product**
It is our hope that the training program continues long beyond the length of this residency, but our end goal for the first six months is to optimize the current materials, making them more test-driven and interactive. We believe these optimizations will allow us to scale, which is the ultimate goal.  Specifically, our goals include an average of 12 students per cohort, a new cohort launching every 3 weeks, running not less than 2 cohorts in parallel. 

**Roadmap**
- EOQ2 Milestone:
    - Prepare PPTs and pre-record tutorials for all key concepts
    Types & Keywords
    Storing Data
    Functions
    Control Flow
    Testing
    Traits
    Standards
    Practice Projects
    - Train the trainers. Equip an additional two instructors to successfully lead cohorts (total 4).
    - Ready to scale to one new cohort per 3 weeks
- EOQ3 Milestone
    - Upgrade Code Academy syllabus
    - Create assignments to be completed within a test-driven-development playground
    - Write quizzes after each concept as a pre-requisite to the following chapter
    - Write a smart contract to issue an NFT certificate of completion to graduates
- EOQ4 Milestone
    - Create a curriculum of pre-work to better equip students for upcoming cohorts
    - Develop and test a qualifying pre-exam

**Comment by cuevasm** [comment]
Brings me great joy to see this application officially come through. As I mentioned over [here](https://github.com/stacksgov/residence-program/issues/14#issuecomment-1063438060), we've received a number of applications and provided feedback and in some cases redirected folks to more suitable positions. (Look out _very soon_ for more exciting Clarity related residency developments 💯 )

Anyway, the Whitelabel team has been so impressive from my first interaction, they come vouched for by Kenny Rogers here at the foundation who used to work there, and are fully prepared to deliver on Clarity Camp in a major way, as well as take advantage of the partnerships and new directions it's primed for.

I fully endorse them for this position and look forward to their presentation to the community. @will-at-stacks is currently scheduling that!

**Comment by proiacm** [comment]
Hi everyone, 

With our Clarity Education residency at its end, we at the Whitelabel team want to provide an end-of-residency update. Working to onboard new developers to the Stacks ecosystem was an incredible experience and we are grateful that we were entrusted with this opportunity. 

### Following is a summary of our achievements over the last year:

- Delivered a total of **6** virtual six-week Clarity Camps with an estimated **400** students total.
- Delivered **2** virtual Instructor Camps for a total of **11** Stacks Chapter leaders to learn to deliver their own local camps.
- Led **1** in-person workshop + hackathon in Miami in partnership with CityCoins, Miami-Dade College, and Venture Miami where we reached an estimated total of **50** students. [Link](https://miamiforeveryone.tech/)
- Led **1** in-person workshop in NYC at EmpireDAO where we reached a total of **5** students. [Link](https://clarity-lang.org/nyc)
- Led **1** in-person Clarity Camp in Austin where we reached a total of **18** students. [Link](https://twitter.com/clarity_lang/status/1556936751263932417?s=20)
- Mentored and delivered a week-long Clarity crash course to Cohort **1** of the BTC Startup Lab where we reached a total of **15** students. [Link](https://twitter.com/btc_albert/status/1545528154260791297?s=20)
- Hosted and judged **4** virtual hackathons with a total of **315** registrations and **35** submissions total:
    - Clarity Universe Camp Hackathon with **33** registrations and **7** submissions. [Link](https://claritycamp3hack.devpost.com/)
    - Builders Edition Clarity Hackathon with **84** registrations and **9** submissions. [Link](https://builders-edition.devpost.com/)
    - Clarity Holiday Hackathon with **108** registrations and **7** submissions. [Link](https://clarity-holiday-hackathon.devpost.com/)
    - Building on Bitcoin Hackathon with **90** registrations and **12** submissions. [Link](https://building-on-btc-hack.devpost.com/)
- Expanded the Clarity Camp curriculum by adding more written content, code examples, tutorials, and assignments. Created a self-paced course including our new content for ongoing Clarity Education past the end of our residency. [Link](https://learn.stacks.org/course/clarity-camp)
- Worked alongside the Stacks Foundation in creating an NFT certificate of completion for Clarity Camp graduates that will reflect in the talent pool directory. [Link](http://stacks.co/jobs)
- Worked alongside Kenny, Stacks Developer Advocate, to create a comprehensive Clarity Assessment with **10** submissions to date. [Link](https://assessment.clarity-lang.org/try)
- Assisted Kenny, Stacks Developer Advocate, in initializing a Building on Bitcoin self-paced course. (In-progress)

Although our Clarity Education residency has come to an end, we still plan to be heavily involved in Stacks and look forward to the continued growth of the ecosystem.

Cheers,

CiaraMaria, Aakanksha, and the rest of the Whitelabel Team
