### ISSUE TITLE
Blockchain Copywriter in Residence:  Content strategy for beginner developers in Clarity

### ISSUE THREAD

**Issue by vicdelgui86** [stacksgov/residence-program#27]
**What's your name/your team's name?**
My name is Víctor Delgado

**Best email on which to contact you?**
emails: vicdelgui86@gmail.com / victoradelgadog@protonmail.com

**Personal Statement**
A few days ago I started to use the Stacks discord channel to ask for help to learn how to program in Clarity, since there is very little material on youtube. I have no previous experience with other coding language.

So, i was interacting with some stacks developers and I realized that the guides/videos that are currently available are designed for developers coming from other languages. This makes it very difficult for people with zero programming knowledge to learn Clarity, which will limit the development of the ecosystem in the long term.

Therefore, I think Stacks has a golden opportunity to develop specialized content for people without programming skills. This will greatly enhance the dev community. We all know that explaining in a simple and thorough way all the necessary processes to learn to program in clarity will be highly valued by all those who want to start from scratch.

**End Product**
From knowing how to install clarinet to how to interpret a smart contract, all processes need to be explained step by step. My idea is to make a specialized blog called "stacks for beginners" so people the current medium content isn't mixed with this one because they have a different user profile. This is the content i plan to do:

1) Step by step guides. of every dev process (Medium Articles) 
2) Scripts for youtube videos. 
3) Content for social media posts (twitter/reddit/discord/telegram)
4) Whitepaper publications 
5) Content for Forum

**Roadmap**
The idea is that this content should be continuous. Ideal time 1 year.
- <Milestone 1> Write 2 medium articles weekly
- <Milestone 2> Write 2 youtube scripts weekly
- <Milestone 3> Write 3 social media posts of each platform weekly
- <Milestone 4> Write 1-2 whitepaper publications weekly
- <Milestone 5> Write 3 forum questions weekly 

**Appendix**

1) Here is a sample of a technical article i made for one client about ERC-721 tokens
https://carboneco.medium.com/what-are-erc-721-tokens-and-how-are-they-mitigating-climate-change-87f229aaaf5

2) A sample about daily news about Terra's blockchain:
https://www.altcoinbuzz.io/cryptocurrency-news/two-reasons-why-terra-became-the-second-largest-defi-platform/

3) Sample about P2E Games on Solana:
https://www.altcoinbuzz.io/top-article/top-5-solana-metaverse-games/

4) Sample about Metaverse:
https://www.altcoinbuzz.io/top-article/why-is-this-project-considered-the-biggest-metaverse-of-all/

5) Sample about NFTs:
https://www.altcoinbuzz.io/cryptocurrency-news/how-are-nfts-entering-in-the-events-ticketing-niche/

I hope this can make you have a better idea of what i've been doing. I am a blockchain copywriter with 4 years of experience in the same sector having worked for 4 different companies and I believe I can experience the clarity learning processes from scratch to write it for you. It would be a dream come true to work for you. 

Victor Delgado

[CV Victor Delgado November 2021 (1).pdf](https://github.com/stacksgov/residence-program/files/8287856/CV.Victor.Delgado.November.2021.1.pdf)

**Comment by will-at-stacks** [comment]
Hi @vicdelgui86 - 
Thanks for reaching out and applying for the residency.  Writing end user friendly summaries on technical topics is definitely something we can always use help with creating.  

That being said, I think it would be best to have you speak with our Developer Advocate (kenny@stacks.org) as a first step.  Kenny writes lots of content and it would be nice to get his feedback on how we could best use some help.  Would you mind reaching out to him?  Once you have a chance to get on the same page with him we will be able to better assess how you could 'plug in'.  

Thanks,
Will
