### ISSUE TITLE
DEFINITIONS FOR A DECENTRALIZED NATION

### ISSUE THREAD

**Issue by christianblaze** [stacksgov/residence-program#28]
**DEFINITIONS FOR A NEW CONSTITUTION**

I believe that Love, as defined herein, has more influence over the actions of a Self, than any other concept.  Love can inspire a Self to risk its own Existence in pursuit of helping realize the Self Purpose of another.  A Self will forgo food and water in the name of Love, disregard real and perceived dangers, and inspires Acts of Kindness.  Many would argue that the freedom to Love and to be Loved supersedes all other needs.

Yet, a Constitution that anchors itself in the definition of Love, does not currently exist on Earth.

An informal, Decentralized Nation that holds the concept of Love as 'most high', has existed on Earth for time immemorial, albeit not officially recognized or organized under a common Constitution.

I propose the creation of such a Constitution to formally recognize the Existence of this Decentralized Nation that believes in the Existence of a higher order... an order emergent and perceivable upon the performance of actions inspired by Love.

For this aim, I present the following Definitions so that they may be considered as the foundation for the Constitution above mentioned:

1. **DEFINITIONS**<br>
a) **Existence**
The quality or state of having the potential to be observed.<br>
b) **Being**
A thing, whether of physical form or otherwise, that has the quality or state of Existence.<br>
c) **Consciousness**
The potential to perceive or become aware of a Being.<br>
d) **Conscious**
The quality or state of actualizing Consciousness.<br>
e) **Conscious Being**
A Being that is Conscious.<br>
f) **Conscious Observer**
A Conscious Being as the subject in their awareness of a Being.<br>  
g) **Self**
A Conscious Observer as the object in their own reflective awareness.<br>
h) **Freewill**
A Self's perceived potential to perform actions that;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;i)  the Self cannot predict, and that
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ii) are free from exclusive or complete determination by any other Being.<br>
i) **Self Purpose**
The Freewill formulation a Self believes to be the purpose of its own Existence. <br>
(j) **Selfless Act**
A Freewill action, performed by a Self (the "Selfless Actor"), with the intention of helping realize the Self Purpose of another Conscious Being (the "Selfless Act Beneficiary"), and is perceived by both, at the time of its execution, as;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;i)  providing no direct or indirect benefit to the Selfless Actor, and is 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ii) detrimental, in some way, to the Selfless Actor.<br>
(k) **Love**
The Self's desire and perceived potential to perform actions that aspire to be Selfless Acts.<br>
(l) **Act of Kindness**
An action, inspired by Love, performed by a Self (the "Kind Actor"), with the intention of helping realize the Self Purpose of another Conscious Being (the "Kind Act Beneficiary"), and is perceived by both, at the time of its execution, as providing a larger benefit for the Kind Act Beneficiary than for the Kind Actor.<br><br>

**BLOCKCHAIN AND IPFS ENTRIES**

For the purpose of memorializing the above definitions as they appear here today, a text file using ANSI encoding has been uploaded to the InterPlanetary File System ("IPFS") and can be viewed at: ipfs://bafybeigmhu7sy2uhqcwzgfohligiomeip3kxahdzoiqrihq3nvf5r3tj5m/ or here: https://bafybeigmhu7sy2uhqcwzgfohligiomeip3kxahdzoiqrihq3nvf5r3tj5m.ipfs.dweb.link/

In addition, a Bitcoin transaction containing the IPFS link has been registered, using the OP_RETURN script opcode. The TxID or hash of the transaction is: 7e808c86069967ce5746ca24b8b253fc99b0e82cf88411e1ca4b9c2bc980cf66 and can be viewed here: https://blockchair.com/bitcoin/transaction/7e808c86069967ce5746ca24b8b253fc99b0e82cf88411e1ca4b9c2bc980cf66

The following hash values may be used to verify the integrity of the file uploaded to the IPFS:
MD5: 3B618C588DA70033EDC3522B2E0B77A7
SHA-256: 7308B9949A8884142EFF352C5DD3BE9ABA273F53F56205EF87CFF5864ADB1B27

**Comment by will-at-stacks** [comment]
Hi @christianblaze -
This is a really inspiring concept.  However, I don't know if its the best fit for a Residency right now as there aren't any actionable steps or deliverables outlined.  It would be great if you could give those items a some thought.  Additionally, once developed, your project might be a more viable candidate for a grant - rather than a residency.  

Thanks,
Will

**Comment by christianblaze** [comment]
> Hi @christianblaze -
> This is a really inspiring concept.  However, I don't know if its the best fit for a Residency right now as there aren't any actionable steps or deliverables outlined.  It would be great if you could give those items a some thought.  Additionally, once developed, your project might be a more viable candidate for a grant - rather than a residency.  
> 
> Thanks,
> Will

Thanks Will. Yes, it is very high-concept right now.
