### ISSUE TITLE
Product Designer-in-Residence (building user-centered Web3 products)

### ISSUE THREAD

**Issue by AJAyanbisi** [stacksgov/residence-program#29]
Product Designer-in-Residence (building user-centered Web3 products)

**What's your name/your team's name?**

AKOREDE J. AYANBISI 

**Best email on which to contact you?**

ajayanbisi@gmail.com

**Personal Statement**
[Explain in 150 words or less the kind of work you'd like to do and why you think it could advance the ecosystem.]

As a creative product designer with an interest in building user-centered products that proffer solutions to real-time problems, I would work as a resident to build/design products that will be of great value to the Stacks ecosystem.

I will channel most of my energy to improving the user experiences of products built on Stacks ecosystem because it is important to help grow and scale products.

Negative impact of bad user experience can diminish the use of the product and, therefore, any desired positive impacts; conversely, designing toward profitability often conflicts with ethical user experience objectives and even causes harm. 

So basically my job will be to build, audit, analyze and improve the user interfaces and user experiences of new and existing products built on Stacks ecosystem.

**End Product**
[Describe in 150 words or less the what you plan to contribute to the community by the end of your residency, e.g. a whitepaper or a series of developer tools.]

I will make sure the products (new or existing products) I work on have great user interfaces and amazing user experiences.

As a product designer, I will make sure my impact is noticed which will be reflected in the products I work on as a resident.

And I will also make sure, I build a dedicated product on Stacks ecosystem to help better the ecosystem and solve a potential problem facing users.

My deliverables will be; 
- To carry out effective UX/UI Research
- High fidelity wireframes and prototype of the products worked on
- To build component libraries
- To write comprehensive design case studies on products worked on
- To improve user interface and user experience of products worked on
- To run UX audit and analysis 
- To be a point of contact and feedback to UX/UI part of products built on Stacks ecosystem 

**Roadmap**
[Break your project down into a simple list of milestones and include the *approximate* dates by when you plan to complete them.]

The activities highlighted above will be ongoing throughout the residency. I will list out milestones using an example of me working on a product/project.

- <Milestone 1> UX Research (3 weeks)
The first milestone will be to carry out UX Research of the product I will be working on, which entails user research, creating user persona, user journey, running competitive analysis, information architecture, ideation, storyboard sketching amongst others.

- <Milestone 2> UI Design (6 - 12 weeks)
This will be to start the UI design of the product based on the collated data from the UX research. And this could take between 6 to 12 weeks or even more depending on how big the project is.

- <Milestone 3> Iteration & User Testing (4 weeks)
This is the stage where iteration and user testing comes in, I will have to test the products to see if it fits what the user wants and also if it fits the market. Then I make iterations to where necessary. 

**Appendix**
[Attach any supplemental materials such as previous work/accolades, notes, diagrams, preliminary research, or community interactions that could support your application.]

Previous Works/Porfolio:

The Responsive Redesign & Visual Improvements of Polkaswap Decentralized Exchange (DEX) Web App — A UX Case Study - https://medium.com/@AJAyanbisi/the-responsive-redesign-visual-improvements-of-polkaswap-decentralized-exchange-dex-web-app-309e4b753824

User-Centered Redesign & Visual Improvements of UBA Mobile Banking App — A UX Case Study - https://medium.com/@AJAyanbisi/user-centered-redesign-visual-improvements-of-uba-mobile-banking-app-a-ux-case-study-382090339a49

Accolades and Positive Feedbacks from the Polkaswap Community: (Images)

![image](https://user-images.githubusercontent.com/66640761/159190320-49203590-fcc5-44cd-b84f-ee4fb1746209.jpeg)
![image](https://user-images.githubusercontent.com/66640761/159190325-0b4072f4-9937-436c-9cb9-36f7dcb6a4db.jpeg)
![image](https://user-images.githubusercontent.com/66640761/159190329-791b6faf-60f9-43bf-a940-9fe7bf1c7ff3.jpeg)
![image](https://user-images.githubusercontent.com/66640761/159190332-46fb6d78-a8a6-471d-88e0-0491e7edffd9.jpeg)

Social Media Links:
Twitter: https://www.twitter.com/aj_ayanbisi
LinkedIn: https://www.linkedin.com/in/ajayanbisi

**Comment by AJAyanbisi** [comment]
> @AJAyanbisi thanks very much for submitting this! I am very excited for our call tomorrow with @cuevasm . This type of a residency would fill a very large community need. It would be great if you could consider how you could also use this residency as a means of attracting more UX/UI designers (and designers in general) into the Stacks ecosystem. Talk soon. Best, Will

Thank you Will. And yes, I will use this opportunity to bring on board and collaborate with good UX/UI designers. Looking forward to our discussion.

**Comment by will-at-stacks** [comment]
# Stacks Resident Program Announcement 

Hello and thank you for your interest in the Stacks Foundation Resident Program!

Please note we are in the process of making some small adjustments to the Residents program and are not accepting new applications at this time. As part of these adjustments we will be migrating the application pipeline over to our newly launched [Grants Dashboard](https://grants.stacks.org/). The GitHub repo of resident applications will remain open, but for reference only. 

We anticipate re-opening the application process on the Grants Dashboard sometime in June 2022.

- If you would like to learn more about the Grants Dashboard please check out this [blog post](https://www.stacks.org/grants-dashboard).
- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Thank you and we look forward to supporting your efforts to build a user-owned internet, powered by Stacks and secured by Bitcoin!
