### ISSUE TITLE
Sustainably bootstrapping Syvita Guild

### ISSUE THREAD

**Issue by 0xAsteria** [stacksgov/residence-program#3]
**What's your name/your team's name?**

Asteria (founder, @syvita)

**Best email on which to contact you?**

asteria@syvita.org - [my PGP key](https://gist.github.com/syvirean/15565a9b45eac5781c94fd6597c16085)

**Personal Statement**

I started Syvita Guild to 

**End Product**

I'm not sure what we will build in the long-term, but we are the largest organisation in the Stacks ecosystem, and I can only see growth accelerating. From MiamiCoin, MiamiPool, Vertex, bitcoin.clar, Zion, EARTH, daoOS, Metaverse to future games built on Stacks, we are on the bleeding-edge of Stacks applications. I'd like funding so I can personally continue work on bootstrapping Syvita into a fully autonomous, onchain organisation and continuing to help lead the community forward. 

**Appendix**

What should I put in here? Do I need to put anything here? 😂

**Comment by cuevasm** [comment]
Hey 👋. I'm not in the group of people that will decide on these things, but watching closely as I'm excited about it. With that, couple questions below: 

A) You'll probably have to get a lot more specific about what the guild would build in a residence capacity to move forward. Would you be able to narrow this down to a specific area the guild is uniquely positioned to impact?

B) I've heard this 'largest organization' in the ecosystem claim a couple times now and just curious what that's based on? Employees? MRR? Treasury? 

Regardless, want to understand better what the guild is hoping to get out of the residence program, mainly why it needs more funding if it's already so successful/large. The program is aimed more at folks just trying to get started or that have a somewhat specific lens through which it would like to start contributing. In general, my understanding of the write up is that the program is a better fit for individuals or very small teams trying to get going.
