### ISSUE TITLE
Tokenomics Resident: Working with new and existing protocols on STX to optimize their tokenomics designs

### ISSUE THREAD

**Issue by aidev42** [stacksgov/residence-program#30]
**What's your name/your team's name?**

Matt O'Connor (@MattySTX)

**Best email on which to contact you?**

mattystx@gmail.com

**Personal Statement**
Tokenomics is arguably the most crucial, and complex, aspect of a crypto project - it covers disciplines/areas such as: game theory, regulatory, UI/UX, governance, tech, and user adoption, growth, retention, and engagement. While there are rarely strictly right or wrong tokenomics decisions, there are always trade offs involved, and when a team or protocol chooses the wrong tradeoff for their relative situation, tokenomics becomes the difference between the protocol thriving, and the protocol barely surviving.

I believe that protocols, teams, and projects building on Stacks need more resources in making the best relative tokenomics decisions. It's unrealistic to find a resident that is an expert in every aspect that tokenomics covers, but the right resource likely has both tradfi and defi experience so they can ask tough questions, poke holes, know what they don't know, and facilitate conversations with subject matter experts when relevant. With a career in tradfi and VC funded tech, and 5 years of DeFi experience, I believe I have the ideal skills and abilities for this role.

**End Product**
I plan to provide ongoing expertise to protocols and teams building on Stacks in their initial tokenomics design choices, and their ongoing refinement of existing tokenomics (for example recent proposed changes to CityCoins protocol). This includes ongoing discussions with myself, compiling deep dive research and building simulations/models that come out of these discussions, and connecting teams with the right subject matter experts where needed (ie legal/regulatory).

Additionally, part of my residency will be to continue to research and document best tokenomics practices across STX and other chains such as ETH and SOL.

**Roadmap**
[Break your project down into a simple list of milestones and include the *approximate* dates by when you plan to complete them.]
- 3 months: publish a compiled directory of resources and best practices across STX project tokenomics
- 6 months: publish a compiled directory of best practices from comparable projects across ETH and SOL chains
- Ongoing: continue to advise new and existing STX projects, and update and maintain directories

**Appendix**
In an unofficial capacity, I have already been an active member in several protocols on STX, such as CityCoins and Arkadiko. Rather than tell you myself, I have asked several builders on Stacks that I have interacted with to post a comment in their own words about how I can benefit STX as a tokenomics resident.

**Comment by tycho1212** [comment]
This is very much needed! There are a lot of tokenomics experiments going on on Stacks. Zest protocol can be helped by someone who has in depth knowledge of the trade-offs of all the models.

@mattroconnor I'd be curious to learn to what extent you have experience making financial models? I think that's quite important for someone in this role to succeed :)

**Comment by paertsxi** [comment]
Matt's opinion and contributions in Arkadiko governance discussions have proven to be incredibly valuable for us. His advice  to the Arkadiko DAO and his influence on policy-making is a prime example of how decentralized organisations can flourish through voluntary member contributions. We hope to have Matt with us in the future and wish him all the best in his professional endeavours. Matt seems very suited for this position, we look forward to his positive impact on the Stacks ecosystem.

**Comment by mattroconnor** [comment]
> This is very much needed! There are a lot of tokenomics experiments going on on Stacks. Zest protocol can be helped by someone who has in depth knowledge of the trade-offs of all the models.
> 
> @mattroconnor I'd be curious to learn to what extent you have experience making financial models? I think that's quite important for someone in this role to succeed :)

Thanks @tycho1212 - I have quite a lot of modeling experience. In traditional finance, I formerly was the senior investment engineer of algorithmic trading at Ray Dalio's hedge fund, Bridgewater Associates, the largest hf in the world by AUM. That job was almost entirely composed of building, testing, and refining financial models. In web 2.0 startups, I've built countless unit economics models and financial projections in the context of business operations, user acquisition, and fundraising, having personally raised VC capital from 3 different institutional investors. And in the STX realm, anyone who has mined with Syvita Mining has likely seen the results of various mining optimization and projections models I built.

The thing I like most about modelling is that to build a good model requires identifying known knowns (formulas) and known unknowns (assumptions/variables), and to think very hard about quantifying the risk of unknown unknowns (risk/volatility/variance).

**Comment by philipdesmedt** [comment]
This is valuable! Matty has been part of several tokenomics discussions on the Arkadiko Discord as well. A great mfer! lol

Good person to have breaking down, analysing and advising on tokenomics 🚀

**Comment by ChienteH** [comment]
Matt has strong finance background. Tokemomics is monetary policy sbx its the first step needed for any project considering issuing its token. I think Matt will be great for this role.

**Comment by pstan26** [comment]
Matt is very sophisticated when it comes to tokenomics, markets, and finance in general. He's added a lot of value for us in the CityCoins community as we make steps to upgrade to CityCoins 2.0. Thank you Matt for all you have done and continue to do for the community generally.

**Comment by Hero-Gamer** [comment]
Matt has been proactive in Stacks, putting thoughts and research out, reached out to the people to get questions answer, I think this attitude will serve him& rest of us very well. 

Many "VE" mechanism modelling being actively discussed and adopted by many other chains and protocols. Lots of innovation around which we can have an awareness to, or innovate ourselves.
