### ISSUE TITLE
Entrepreneur-in-Residence to research and design Bitcoin and Smart Contract adoption solutions in local communities in Kenya

### ISSUE THREAD

**Issue by martveeken** [stacksgov/residence-program#31]
Title: Entrepreneur-in-Residence to research and design bitcoin and smart contract adoption solutions in local communities in Kenya

**What's your name/your team's name?**
Mart Veeken - Labl Fashion
Isaac Waithaka - Labl Fashion

**Best email on which to contact you?**
[[mart@labl-fashion.com](mailto:mart@labl-fashion.com)](mailto:mart@labl-fashion.com)

**Personal Statement** *[Explain in 150 words or less the kind of work you'd like to do and why you think it could advance the ecosystem.]*
Labl is a social & sustainable clothing production facility in Kenya. The facility is part of a local Kenyan community cooperative. From seed (local small holder farmers) to garment, the whole value chain is being produced in this community, generating jobs, sharing profits and introducing regenerative agriculture.

The bitcoin ecosystem is designed for supporting local communities. Instant borderless payments, community wallets, nft’s for supply chain transparency, smart contract for decision making. The bitcoin network enhanced by the capabilities of Stacks could make this possible and provide a unique opportunity to increase welfare and livelihoods in remote local communities.

However great this promise, the key to successful adoption is to have a deep understanding in the users. This project is researching people in local communities in Kenya, ideate and co-create opportunities for bitcoin and Stacks and provide concepts and stories to the bitcoin community for accelerating bitcoin adoption.

**End Product** *[Describe in 150 words or less the what you plan to contribute to the community by the end of your residency, e.g. a whitepaper or a series of developer tools.]*

The result of this research and design project is a deep understanding in potential users of the bitcoin and stacks technology living in local communities in Africa. With focus groups and co-creation workshop together with locals, we will ideate and conceptualise ideas that will be published and can be used by the bitcoin community. All research data, including notes, transcriptions of interviews and quantitative data, will be publicly available for anyone who is interested to use it.

Next up are monthly stories that celebrate the success of bitcoin in local communities in Africa. These success stories can help the bitcoin community to increase global positive awareness.

At last, this research will design communication and educational materials that can help people in local communities to adopt bitcoin. These highly visual materials (animations, presentations, visuals, infographics) can be used by anyone that has a similar mission; accelerate bitcoin adoption.

**Roadmap** *[Break your project down into a simple list of milestones and include the approximate dates by when you plan to complete them.]*

This roadmap will follow the classic double diamond design approach rolled out in 4 quarters. It is an iterative process where new learnings and insights will reinforce outcomes.

- Q1 - Discover: Context mapping, interviews and focus groups, quantitative research
    - Deliverables: Research outcomes
- Q2 - Define: User journey mapping, personas, insight analysis
    - Deliverables: Insights, user journey and opportunity map
- Q3 - Develop: design sprints, value proposition workshops, service design
    - Deliverables: Ideas and concepts
- Q4 - Deliver: Prototyping and user testing
    - Deliverables: Tested prototypes, (visual) communication and educational materials

Collaboration
We are currently exploring collaboration with [Master Guantai](https://twitter.com/Bitcoinmtaani) who is currently setting up a Bitcoin Educational platform in Kenya to accelerate Bitcoin adoption.

**Appendix**
[Attach any supplemental materials such as previous work/accolades, notes, diagrams, preliminary research, or community interactions that could support your application.]

We are planning to openly publish all the research findings on the Bitcoin Experience website: https://www.bitcoinexperience.xyz/

The website of Labl Fashion: https://www.labl-fashion.com/

An example animation for Bitcoin that I've made: https://youtu.be/qQ08JyrmoAA

**Comment by will-at-stacks** [comment]
# Stacks Resident Program Announcement 

Hello and thank you for your interest in the Stacks Foundation Resident Program!

Please note we are in the process of making some small adjustments to the Residents program and are not accepting new applications at this time. As part of these adjustments we will be migrating the application pipeline over to our newly launched [Grants Dashboard](https://grants.stacks.org/). The GitHub repo of resident applications will remain open, but for reference only. 

We anticipate re-opening the application process on the Grants Dashboard sometime in June 2022.

- If you would like to learn more about the Grants Dashboard please check out this [blog post](https://www.stacks.org/grants-dashboard).
- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Thank you and we look forward to supporting your efforts to build a user-owned internet, powered by Stacks and secured by Bitcoin!
