### ISSUE TITLE
One line describing your role and work as a Resident, e.g. "Entrepreneur-in-Residence exploring Stacking-based business models"

### ISSUE THREAD

**Issue by Cryptojourney1** [stacksgov/residence-program#32]
**What's your name/your team's name?**
CryptoJourney. My name is Renee LaRocca
**Best email on which to contact you?**
laroccarenee@gmail.com
**Personal Statement**
My passion is to advance the ecosystem by offering my expertise as a product manager to develop and launch products/applications. I am a seasoned product management professional who has successfully led and managed global product management and development teams at an executive level. I have over 30 years developing and launching products and I want to transfer my skills into advancing the ecosystem. My formal education includes a BS in Mechanical Engineering, MBA and MS in Engineering Management and I have worked primarily in manufacturing but also have experience in health care and finance.  A few ideas using the CityCoin concept as a foundation:

1.	Creating a Local Investing Network (LIN) to replace the current lending practices.  
2.	Create a program to offer mining operations with products to help them educate the community and provide funding via mining. 
3.	Create a hands on exhibit that can be used at Science Museums.

**End Product**

I see myself as a freelance product management specialist eager to help teams create clear actionable plans and complete market research. I love to work on teams where we are excited about our mission and creating innovative products. I am known for helping solve difficult problems and get programs that have fallen off the tracks back on. 

- I will create product plans for each project with resource requirements, budget, action steps and timelines.
- I will create market plans for each category assigned to me.
- I will create templates for other teams to use for their product plans.

**Roadmap**

1. If I am fortunate enough to be part of the residency program, I would focus on whatever team needed product management leadership/support. 

2. If I worked on developing a LIN project this is what my initial timeline to get funding could look

[R. LaRocca resume 03.28.2022.pdf](https://github.com/stacksgov/residence-program/files/8457683/R.LaRocca.resume.03.28.2022.pdf)
:
- Complete microbusiness LIN class through WA state - May 1, 2022
- Create product plan - June 1, 2022
- Get funding to hire developers, and pay for expenses - September 2022

**Appendix**
[Attach any supplemental materials such as previous work/accolades, notes, diagrams, preliminary research, or community interactions that could support your application.]

**Comment by will-at-stacks** [comment]
# Stacks Resident Program Announcement 

Hello and thank you for your interest in the Stacks Foundation Resident Program!

Please note we are in the process of making some small adjustments to the Residents program and are not accepting new applications at this time. As part of these adjustments we will be migrating the application pipeline over to our newly launched [Grants Dashboard](https://grants.stacks.org/). The GitHub repo of resident applications will remain open, but for reference only. 

We anticipate re-opening the application process on the Grants Dashboard sometime in June 2022.

- If you would like to learn more about the Grants Dashboard please check out this [blog post](https://www.stacks.org/grants-dashboard).
- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Thank you and we look forward to supporting your efforts to build a user-owned internet, powered by Stacks and secured by Bitcoin!
