### ISSUE TITLE
Entrepreneur-in-Residence exploring DeFI VC

### ISSUE THREAD

**Issue by patrickocr** [stacksgov/residence-program#33]
**What's your name/your team's name?**
Patrick O'Connor-Read / unVC

**Best email on which to contact you?**
patrickocr@gmail.com / patrickocr@zolayola.com

**Personal Statement**
[Explain in 150 words or less the kind of work you'd like to do and why you think it could advance the ecosystem.]

I'm building out a decentralised marketplace for investing in startups using a sequential-reveal peer review process, i.e. experts review startups in isolation, then get to compare their analysis to other parties views once submitted, limiting group think. 

On the platform side, we build a bridge between institutional capital and startups, enabling capital to be targeted using thematic and algorithmic criteria to target underserved niches and emerging themes, with a view to anti-pattern / outlier recognition.

From an intelligence perspective, we provide transparency to an opaque process, connecting capital to opportunity across a fragmented ecocsystem, enabling and recording financial transactions via reconciliation to a PoW blockchain.

**End Product**
[Describe in 150 words or less the what you plan to contribute to the community by the end of your residency, e.g. a whitepaper or a series of developer tools.]

1. I'd like to better understand how to drive STX and think that engaged experimentation/extended "play" wld enable this. 
2. A research paper cld be a tangible output, but my inclination leans towards more of a series of Medium posts - reach is wider.
3. The major goal would be the creation of a MVP, securing LP's to invest in VC's to invest in startups. 

I've looked at yr Grant process and that cld work but seems more hierarchical when I'm looking for meaningful collaboration. I've also looked at yr Accelerator but that seems too regimented for my style - I think you've over scheduled activities. I like the hands off, but within reach, approach of extended thinking & doing of an EIR model.

**Roadmap**
[Break your project down into a simple list of milestones and include the *approximate* dates by when you plan to complete them.]
May <Milestone 1> Soft Set-Up; Secure Buy-In, Establish Relations, Set-Up Sessions; i.e. Smart Contract Coding & Rvw.
June <Milestone 2> Architecture; Review and Amend existing Solution Architecture diagrams/documentation.
July  <Milestone 3> Smart Contracts; optimise workflow to create/test and reconcile to BTC DLT.
Aug  <Milestone 4> MVP UI for sign up, metrics, review flow, marketplace UX.
Spt+ <Milestone 5> On-board startups via API to targets, i.e. Founders Institute, possible LP & VC's.

**Appendix**
[Attach any supplemental materials such as previous work/accolades, notes, diagrams, preliminary research, or community interactions that could support your application.]

[unVC commercial.pdf](https://github.com/stacksgov/residence-program/files/8559202/unVC.commercial.pdf)

[unVC technical.pdf](https://github.com/stacksgov/residence-program/files/8559205/unVC.technical.pdf)

**Comment by will-at-stacks** [comment]
Hi @patrickocr - Thank you for the application.  We are in the process of making some slight adjustments to the Residents program and have paused on taking new Residents on at the moment.  However, I will discuss your application subject with @jennymith and let you know if we have any initial thoughts.  We plan to re-open applications in June.

Best,
Will

**Comment by patrickocr** [comment]
Thanks Will. Welcome yr + Jenny's thoughts in due course. Best, Patrick
