### ISSUE TITLE
Discreet Log Contracts (DLC) Residence

### ISSUE THREAD

**Issue by Akibalogh** [stacksgov/residence-program#36]
**What's your name/your team's name?**
DLC.link

**Best email on which to contact you?**
aki@dlc.link, jesse@dlc.link, matt@dlc.link

**Personal Statement**
DLCs (Discreet Log Contracts) are 2-of-3 multisig wallets where one of the parties is an oracle that independently referees the outcome. To date, DLCs have been used for academic purposes, mainly focused on theoretical examples using sports betting. However, we see DLCs as a valuable escrow service that lets smart contracts interact with native Bitcoin.
Stacks and Clarity were designed to bring smart contracts to Bitcoin. But today, Stacks can’t write to Bitcoin, forcing Stacks teams to use wrapped Bitcoin in their apps. Our DLC bridge lets Stacks apps use native Bitcoin, representing a major unlock across various use cases ranging from non-custodial lending to proof-of-reserves for minting Bitcoin-backed wrapped stablecoins.

Escrow is a basic financial primitive that enables powerful financial use cases in DeFi, spanning lending, options, futures and insurance applications. Unlocking liquidity on Bitcoin (the largest crypto network) represents a major strategic opportunity for Stacks.

In order to realize these benefits, Stacks teams need to build in DLC-enabled infrastructure into their apps and wallets. With this residency, we’re looking to support the Stacks community in implementing DLCs. 
Our primary goal will be to support the development of DLC-specific projects within Stacks through pilots, hands-on training and hackathons. Secondly, we will be promoting engagement through virtual and in-person events such as office hours, hackathons and conferences as well as creating technical documentation and marketing materials to build awareness around use cases enabled through DLCs.

**End Product**
Our end goal for the first six months of the residency is to facilitate the creation of at least 10 active pilots using DLCs within Stacks teams and to create an environment of strong support and engagement around DLCs.
To support these pilots, we will be available for structured interactions (e.g. office hours) and for ad-hoc requests. In order to ensure alignment with Stacks Foundation’s priorities, we will facilitate a quarterly community call around accomplishments and tactical goals.

**Roadmap**

**Q2 Milestones (complete)**
- Launch DLC contracts and documentation
- Publish website and lightpaper 
- Run Stacks Pre-accelerator Hackathon

**Q3 Milestones**
- Two prototypes launched (e.g. Arkadiko)
- Minimum 5 active use cases with Stacks teams
- Importable DLC trait (library) in Clarity
- Launch DLC wallet library
- Launch DLC Oracle network closed alpha
- Technical whitepaper with tokenomics published
- Build a packaged training module (e.g. a tutorial with a live example)
- Ongoing support for Stacks teams using DLCs via weekly office hours
- Ongoing thought leadership around advanced DLC innovations (e.g. transferability, Lightning network integration)

**Q4 Milestones**
- Minimum 10 active pilots with Stacks teams
- DLC oracle network beta launch with least independent 2 node operators
- Token launch plans marketed within Stacks
- Hiro wallet DLC integration complete
- Support for more complex DLC payout curves
- Ongoing support for Stacks teams using DLCs via office hours, hackathons and hands-on training programs
- Ongoing support and thought leadership around advanced DLC innovations (e.g. transferability, Lightning network)

**Q1 and Q2 2023 Milestones**
- Production-grade oracle network and ongoing operational support
- Token private round launched within Stacks
- Additional support for more DLC payout curves and capabilities
- Wallet integrations upon request
- Ongoing support for Stacks teams using DLCs via office hours, hackathons and hands-on training programs
- Ongoing support around advanced DLC innovations (e.g. transferability, Lightning network)

**Appendix**

Core Team
Aki Balogh, CEO, New York (https://www.linkedin.com/in/akibalogh/)
Aki invented the predominant method for content optimization for SEO via topic modeling and founded MarketMuse to bring it to market. MarketMuse is an AI-driven content intelligence platform that was named the “undisputed leader in content optimization” in 2019. Previously, Aki focused on scalable data infrastructures at InfiniDB and OpenView Venture Partners and designed decision-support systems for Fortune 500 clients at Diamond.
 
Jesse Eisenberg, CTO, Budapest (https://www.linkedin.com/in/jesses16)
Jesse has served in a number of software engineering and engineering management roles, spanning Pivotal Labs, MoPub and Twitter. He’s a serial entrepreneur excited to put his knowledge of blockchain to work.

Matt Bombard, Product, New Jersey (https://www.linkedin.com/in/matthewbombard/)
Matt comes from a financial services background in technology audit. He is passionate about blockchain technology, emerging DeFi challenges, financial derivatives, and analytics.

**Comment by unclemantis** [comment]
Just got introduced to Oracles today! I had no idea! Thank you!

**Comment by Hero-Gamer** [comment]
**Use case**
- The use case as I understand it from the interview Jakeblockchain did with Aki, was that on the consumer level, you can almost do what some of the smart contract does on Stacks network, such as non-custodial locking up your fund, then later unlocking the fund based on some conditions being met, DLC appears to be able to unlocks this function for the Bitcoin side. 
- A bit like the feel of how BOOM smart contract locking up STX fund for a period of time (for Stacking), balance cannot be used (unavailable) but still in your wallet. 
- I think should be able to unlock some interesting and practical native Bitcoin use cases. +1

**Bitcoin derivation path**
- I wonder whether the conversation around standardizing Bitcoin derivation path will affect Aki's work? Or maybe it's worth having Aki be part of this conversation. 
- Please see the ongoing conversation happening right now on Stacks Forum: https://forum.stacks.org/t/rfc-standardizing-on-bitcoin-derivation-paths/13394  (@Akibalogh if this is relevant, please feel free to chime in on Stacks Forum)
- This derivation path conversation originated from here: https://github.com/hirosystems/stacks-wallet-web/issues/2402

**About**
- From the podcast, Aki appears to be entrepreneurial, and a problem solver, so I'd imagine if anything not satisfactory about DLC he would find a way to solve it.

**Comment by bill3129066** [comment]
It's Aidan from A.S.K. Protocol (http://twitter.com/ASK_Protocol). Definitely think DLC's residence will make Stacks community better & fundamentally make our protocol uniquely stronger. 

Besides, I appreciate the idea of office hours they proposed. I talked to Matt, their business analyst, and that conversation helped us immensely, so I think it will also benefit others as well.

**Comment by abdelghafour** [comment]
@Hero-Gamer 👍, this is a powerful feature on bitcoin that allows locking your BTC without having to give up custody, because they are still in your wallet. 

Things become very interesting when you verify that locking was done in the bitcoin chain using merkle proof and something like this: https://github.com/jcnelson/clarity-bitcoin/blob/main/clarity-bitcoin.clar#L742 on stacks, to bridge a non-custodial locking into building protocols that back their liquidity with native bitcoin (like https://tali.finance/). 

DLCs will allow for elegantly onboarding liquidity from bitcoin into stacks for use cases like lending, trading, or just generating yields for bitcoin holders in a non-custodial manner.

**Comment by jennymith** [comment]
> **What's your name/your team's name?** DLC.link
> 
> **Best email on which to contact you?** [aki@dlc.link](mailto:aki@dlc.link), [jesse@dlc.link](mailto:jesse@dlc.link), [matt@dlc.link](mailto:matt@dlc.link)
> 
> **Personal Statement** DLCs (Discreet Log Contracts) are 2-of-3 multisig wallets where one of the parties is an oracle that independently referees the outcome. To date, DLCs have been used for academic purposes, mainly focused on theoretical examples using sports betting. However, we see DLCs as a valuable escrow service that lets smart contracts interact with native Bitcoin. Stacks and Clarity were designed to bring smart contracts to Bitcoin. But today, Stacks can’t write to Bitcoin, forcing Stacks teams to use wrapped Bitcoin in their apps. Our DLC bridge lets Stacks apps use native Bitcoin, representing a major unlock across various use cases ranging from non-custodial lending to proof-of-reserves for minting Bitcoin-backed wrapped stablecoins.
> 
> Escrow is a basic financial primitive that enables powerful financial use cases in DeFi, spanning lending, options, futures and insurance applications. Unlocking liquidity on Bitcoin (the largest crypto network) represents a major strategic opportunity for Stacks.
> 
> In order to realize these benefits, Stacks teams need to build in DLC-enabled infrastructure into their apps and wallets. With this residency, we’re looking to support the Stacks community in implementing DLCs. Our primary goal will be to support the development of DLC-specific projects within Stacks through pilots, hands-on training and hackathons. Secondly, we will be promoting engagement through virtual and in-person events such as office hours, hackathons and conferences as well as creating technical documentation and marketing materials to build awareness around use cases enabled through DLCs.
> 
> **End Product** Our end goal for the first six months of the residency is to facilitate the creation of at least 10 active pilots using DLCs within Stacks teams and to create an environment of strong support and engagement around DLCs. To support these pilots, we will be available for structured interactions (e.g. office hours) and for ad-hoc requests. In order to ensure alignment with Stacks Foundation’s priorities, we will facilitate a quarterly community call around accomplishments and tactical goals.
> 
> **Roadmap**
> 
> **Q2 Milestones (complete)**
> 
>     * Launch DLC contracts and documentation
> 
>     * Publish website and lightpaper
> 
>     * Run Stacks Pre-accelerator Hackathon
> 
> 
> **Q3 Milestones**
> 
>     * Two prototypes launched (e.g. Arkadiko)
> 
>     * Minimum 5 active use cases with Stacks teams
> 
>     * Importable DLC trait (library) in Clarity
> 
>     * Launch DLC wallet library
> 
>     * Launch DLC Oracle network closed alpha
> 
>     * Technical whitepaper with tokenomics published
> 
>     * Build a packaged training module (e.g. a tutorial with a live example)
> 
>     * Ongoing support for Stacks teams using DLCs via weekly office hours
> 
>     * Ongoing thought leadership around advanced DLC innovations (e.g. transferability, Lightning network integration)
> 
> 
> **Q4 Milestones**
> 
>     * Minimum 10 active pilots with Stacks teams
> 
>     * DLC oracle network beta launch with least independent 2 node operators
> 
>     * Token launch plans marketed within Stacks
> 
>     * Hiro wallet DLC integration complete
> 
>     * Support for more complex DLC payout curves
> 
>     * Ongoing support for Stacks teams using DLCs via office hours, hackathons and hands-on training programs
> 
>     * Ongoing support and thought leadership around advanced DLC innovations (e.g. transferability, Lightning network)
> 
> 
> **Q1 and Q2 2023 Milestones**
> 
>     * Production-grade oracle network and ongoing operational support
> 
>     * Token private round launched within Stacks
> 
>     * Additional support for more DLC payout curves and capabilities
> 
>     * Wallet integrations upon request
> 
>     * Ongoing support for Stacks teams using DLCs via office hours, hackathons and hands-on training programs
> 
>     * Ongoing support around advanced DLC innovations (e.g. transferability, Lightning network)
> 
> 
> **Appendix**
> 
> Core Team Aki Balogh, CEO, New York (https://www.linkedin.com/in/akibalogh/) Aki invented the predominant method for content optimization for SEO via topic modeling and founded MarketMuse to bring it to market. MarketMuse is an AI-driven content intelligence platform that was named the “undisputed leader in content optimization” in 2019. Previously, Aki focused on scalable data infrastructures at InfiniDB and OpenView Venture Partners and designed decision-support systems for Fortune 500 clients at Diamond.
> 
> Jesse Eisenberg, CTO, Budapest (https://www.linkedin.com/in/jesses16) Jesse has served in a number of software engineering and engineering management roles, spanning Pivotal Labs, MoPub and Twitter. He’s a serial entrepreneur excited to put his knowledge of blockchain to work.
> 
> Matt Bombard, Product, New Jersey (https://www.linkedin.com/in/matthewbombard/) Matt comes from a financial services background in technology audit. He is passionate about blockchain technology, emerging DeFi challenges, financial derivatives, and analytics.

Quick application update: Considering the scope and projected impact of this project, we are currently working with @owenstrevor to explore a different and perhaps more effective support mechanism/arrangement than a residency.
