### ISSUE TITLE
Grants Marketing & Communication Residency

### ISSUE THREAD

**Issue by vanesvibes** [stacksgov/residence-program#38]
**What's your name?**
Vane Vargas

**Best email on which to contact you?**
Vane@vanesvibes.com

**Personal Statement**
As a Grants Ambassador, I was able to get first hand experience on how the program works and was able to connect with grantees and their projects on a deeper level. One of the obstacles grantees are facing is how to gain more exposure and amplify their messaging so that their project reaches the right people and is successful. 

During my time in the Residency Program, I’d like to leverage content and social media to raise awareness of the grants program itself, as well as the amazing teams/projects building on Stacks via the grants. Additionally, I’d like provide hands-on coaching/consulting to grantees, ensuring that they have a seamless and rewarding experience, from the moment they apply for a grant through completion of their grant. 

I believe that the Stacks ecosystem is only as good as the communities it serves. The more time and effort we spend making sure that these communities thrive and gain exposure, the more attractive the Stacks building experience will be to other builders, founders, and entrepreneurs.

**Goals**

- Raise awareness for Grants Program
- Expand marketing for projects coming out of Grants Program
- Lower barrier of entry for potential grantees
- Build Grantee journey from start to completion focusing on enhancing their experience. From coaching potential grantees on writing quality applications to follow up and support throughout milestone achievements.

**Roadmap**

3 months (Q3 2022)
* Weekly blog post highlighting most recent updates on current Grants projects
* Host 2 Monthly AMAs with Will & other team members on Grants Program 
* Biweekly Twitter Spaces focusing on Grants operational FAQs and highlighting Grantees
* Support with monthly community call 
* GH Posts on with updates on applications and on-going grants.
* Weekly content calendar for Twitter 
* Support Rick (Social Media Lead at the Foundation) with content creation like videos, Grant threads, Discord that will help Grants get more exposure

**Comment by joberding** [comment]
There is definitely a need for this to help residents, grantees and the foundation get the word out about the grant program and exposure for projects.

**Comment by Ceramicwhite** [comment]
Vanessa is beloved by her coworkers and grantees a like. It's an absolute pleasure working with her supporting grantees and I know she will continue to bring tons of value to the community. Vanessa has a strong passion for Stacks and its community and  I know the community is very fond of her and are all completely in support of her application. Hope we get the opportunity to continue working together.

**Comment by diopitis** [comment]
Vane has been an amazing grants ambassador and having her from start to finish help grantees through the grant process would be invaluable, she already has really benefited the community. Her residency would positions any grantee for success to deliver an impactful project to the community!

**Comment by jennymith** [comment]
Hi @vanesvibes, thanks again for working with us throughout this process. As communicated on yesterday's call, we will no longer be moving forward with your residency. While we acknowledge that the work you've done for the Grants Program has been valuable, the scope of work proposed here is not quite a fit for the Residence Program, which focuses on longer term research & development projects. A more detailed explanation has been posted [here as well](https://github.com/stacksgov/residence-program/issues/35#issuecomment-1213451144). 

We acknowledge the unexpected shift from the Ambassador Program to Residence Program and understand that you may not have planned for this situation. As such, we will be disbursing a stipend to cover the time and effort you've spent on this process. If you have any questions or feedback that you'd like us to address, please let me know.
