### ISSUE TITLE
"Entrepreneur-in-Residence improving critical thinking through Stacks"

### ISSUE THREAD

**Issue by chamirag** [stacksgov/residence-program#4]
**What's your name/your team's name?**

Chamira Gamage & Jay Patel / Thinkrs: https://www.thinkrs.io/

**Best email on which to contact you?**

chamiragamage7@gmail.com

**Personal Statement**
[Explain in 150 words or less the kind of work you'd like to do and why you think it could advance the ecosystem.]

We want to contribute to Stacks’s impact in a meaningful way by associating our unique mission to its movement.

Thinkrs helps anyone identify misinformation, polarization and media bias; some of the greatest problems of our time. Through a unique set of tools, our ecosystem seeks to tackle this problem through critical thinking. Within this is a gamified environment, which makes collective knowledge sharing unique. We are also looking to provide non-partisan voting information alongside civic engagement communities in Atlanta.

We feel this mission will be fulfilled in the Stacks community, alongside existing accelerator projects which complement our objectives and enhance people’s sovereignty over their lives. We also believe Thinkrs can assist in building a cultural appreciation of blockchain within the Web 2.0 world, thus acting as a bridge and onboarding project.

We want to bring clarity to content consumers globally, in partnership with Stacks, while building with 'clarity', itself.

**End Product**
[Describe in 150 words or less the what you plan to contribute to the community by the end of your residency, e.g. a whitepaper or a series of developer tools.]

By the end of our residency, we believe we can build an engaged civic community with projects like Citycoins. This would enable a city to engage directly with its constituents on how its BTC stack could be utilised (greater direct democracy!). This model can grow as CityCoin expands to other cities.

We can conduct interviews and collective discussions/forums via our Thinkrs social media tools and could be utilised to promote Stacks projects and more broadly Web 3.0 to mainstream society, engaging locals in a unique, nuanced way that touches on issues relevant to their city.

Lastly we hope to produce a thorough Whitepaper on the impact of Thinkrs on critical thinking around the world, specifically in conjunction with the Stacks ecosystem. This can be a use case for STX Social Impact, shaping a cohesive narrative alongside projects such as Citycoins, Sigle etc. 

**Roadmap**
[Break your project down into a simple list of milestones and include the *approximate* dates by when you plan to complete them.]
- <Milestone 1>
v1.0 of Thinkrs ecosystem released: context detector, news aggregator, social cafe spaces (Jan 2022)
- <Milestone 2>
- Release 'Clarity Coin' (tied to STX and/or BTC) to interact in our gamified point-based ecosystem (March 2022)
-  <Milestone 3>
- Begin Thinkrs rollout in India to promote critical thinking while reading english-based news media (April 2022)
- <Milestone 4>
- Release a set of meaningful, functional NFTs built off STX to grow the Thinkrs and STX community for the long term. (April 2022)
- <Milestone 5>
- Release governance token for members, giving individuals voting rights over the direction of proposals within Thinkrs (May 2022)
- <Milestone 6>
- Collaborate with Citycoin and other localised projects to enhance local impact and community engagement (June 2022)
- <Milestone 7>
- Get a minimum of 250,000 users around the world consuming news and participating in the Thinkrs ecosystem (Nov 2022)

**Appendix**
[Attach any supplemental materials such as previous work/accolades, notes, diagrams, preliminary research, or community interactions that could support your application.]

- Thinkrs Whitepaper (original v1.0):
- https://www.thinkrs.io/our-whitepaper
- Guest on the Pomp Podcast in December 2020; talked on a pardon for Julian Assange and discussed Thinkrs as a solution for misinformation and media bias: https://youtu.be/RVZZszbSvWs
- Julian Assange briefing on ‘threats to the freedom of press in the 21st century’ speaking for Amnesty International: 
- https://youtu.be/-mfANxYJM6k
- Chamira’s Publications:
- https://www.researchgate.net/profile/Chamira-Gamage
- Globalization and Environment: Discourse, Policies and Practices, publication date, Aug 1, 2015, Rawat publications. 
- Globalisation of culture in the context of Globalism/Localism and homogenization/Fragmentation Debates, Jan 2010 , Global South-Sephis e Magazine Vol. 6, No. 1
- Members of Humane Tech Society
- LinkedIn Profiles:
- https://www.linkedin.com/in/chamirag/
- https://www.linkedin.com/in/jay-patel-3a741030/

**Comment by jennymith** [comment]
Hi @chamirag, thanks again to you and your partner for walking us through your proposal. Thinkrs is definitely an interesting platform with the potential to improve civic engagement in certain communities. However, after much discussion, we have decided not to move forward with your application. 

While the mission to improve critical thinking is certainly one that resonates with us, it is also quite a broad initiative that seems orthogonal to the needs of Stacks community members at the moment. Currently, the most pressing issues facing the Stacks community are those concerning building (better developer tools, improvements to network scalability, etc.) and governance (off and on-chain decision-making, reputation building, and rewards distribution). These are the areas we encourage you to look into should you decide to apply again in future.

In the meantime, if there are related projects that you'd be interested in exploring, I recommend looking into the [Stacks Grants Program](https://github.com/stacksgov/Stacks-Grants/issues) as a way to get started. Although we were not able to work with you as residents this time around, we'd love to help you continue your work on Stacks where possible.

**Comment by chamirag** [comment]
Hi Jenny,

Thanks again for yours, Mitchell’s and Brittnays time last week.

And for the detailed feedback. Absolutely will apply for the grants program
and keen to build through the STX ecosystem in future.

Chamira
