### ISSUE TITLE
Researcher-in-Residence - Offramp and Utility for Africa 

### ISSUE THREAD

**Issue by uchibeke** [stacksgov/residence-program#40]
### **Focus Areas/Scope of Work**
The utility of Bitcoin is still limited especially in emerging countries that could benefit the most from Bitcoin.

This role will explore options for enabling an offramp from bitcoin directly to local products and services, thus increasing financial inclusion and helping to achieve the original goal of Bitcoin, as peer-to-peer exchange of value

### **Potential Deliverables**
- Outlook and opportunities of Bitcoin in Africa<Product 1>
- Existing payment rails
- Opportunities for connecting Bitcoin with Existing rail
- An MVP for offramp from Bitcoin to a local product/service. For example, Bitcoin to Mpesa mobile money (Momo) in Kenya with users paying Bitcoin to get Momo

### **Background & Skills**
The Resident should have experience as a Product Manager or Developer and must reside or have grown up in Africa. They should have first-hand experience using local rails

Furthermore, the Resident should:
- Have experience working in bitcoin or a Crypto project
- Published previous research OR built a _live_ Payment app
- Ability to be self-directed with a portfolio of and history of work

**Comment by will-corcoran** [comment]
Hi @uchibeke ,

Thank you for your interest in the Stacks Residency program and for the time you invested in your application. We appreciate your patience as we completed our review process.

After thorough evaluation, we have concluded that the current focus of the Residency program, which emphasizes collaboration with the Stacks Core Engineering Working Group by subject matter experts, may not align closely with the nature of your proposed work. The program is specifically tailored to support individuals who are deeply involved in the core technical development of the Stacks ecosystem.

For insights into the specific goals and ongoing projects of the Stacks Core Engineering teams, we encourage you to join our [discussion board](https://github.com/orgs/stacks-network/discussions). This platform will provide you with a clearer understanding of our current needs and focus areas. We hope this will assist you in refining your proposal to better align with these objectives, and we welcome you to reapply in the future.

Thank you once again for your interest in contributing to the Stacks ecosystem. We wish you the best in your future endeavors.

Warm regards,

Will Corcoran
Ecosystem Program Manager
