### ISSUE TITLE
Develop a better Bitcoin wallet via account abstraction (AA)

### ISSUE THREAD

**Issue by hoho-yin** [stacksgov/residence-program#42]
Develop a better Bitcoin wallet fully usable and interoperable with other smart contract blockchains via account abstraction (AA)

**Name**
Jel Ying

**Email**
jelying0823@gmail.com

**Personal Statement**
The significant account abstraction (AA) upgrade makes blockchain accounts programmable via smart contracts to allow users freely self-define the logics and settings of their accounts. Based on AA our new crypto wallet can improve the functionalities, performance and user experience of user accounts as good as Web2 while maintaining the decentralization of Web3. Unlike other wallets, instead of providing all wallet functionalities and features by ourselves, we gather third-party smart contract developers to develop their account applications in our wallet. In this way we build an ecosystem like App Store in our wallet with all different third-party account services to better meet different user demands and make our wallet fully customized for each user. 

**End Product**
Our AA wallet will be programmable fully defined and set by users’ smart contracts to make users have better blockchain accounts and meet their different personalized demands for using Bitcoin. In the design of our wallet, rather than providing all account functions and features for users by ourselves,  we will build an ecosystem for third-party smart contract developers and Bitcoin service providers to develop their third-party account applications which help users setup their accounts easily and better meet their different kinds of user demands in our wallet like App Store.

There are two kinds of third-party smart contract account applications in our wallet. One is account management applications which assist users to setup and manage their accounts themselves via smart contracts, and account interaction applications which help users use smart contracts in their accounts to directly interact with the contracts of others like DApps and other users. We will present several use cases for these two kinds of applications.

To facilitate the two kinds of applications above, we will enable them to connect to existing Web2 account services to make smart contract accounts in our wallet as usable as Web2 accounts like user-friendly account login and recovery. As our wallet is constructed based on smart contracts, we will optimize the smart contracts of our wallet and use scalability techniques like layer2 rollup to improve the performance of our wallet in throughput and overhead for higher efficiency. 

We will also build universal account standards for different kinds of applications to fully compatible and interoperable with each other based on the same account data keeping in user sides.  With applicable and transferable account data, Users can freely switch among different account applications to avoid single point of failure for decentralization and autonomy. For example, when one 2FA login service is down, users can still login via another one with their 2FA account data even if they didn’t register in other 2FA login applications before. 

**Roadmap**
May ~ June 2023: technical research, product design 
July ~ Aug 2023: technical development, testing and implementation
Sept ~ Oct 2023: marketing research and promotion to attract and preserve users 
Nov ~ Dec 2023: business development for attracting third-party account application developers and account service providers

**Appendix**
https://drive.google.com/file/d/1u0uONWl99sXoPNjWsGCtjUd8Es3-v6m3/view?usp=share_link

**Comment by will-corcoran** [comment]
Hi @hoho-yin 

Thank you very much for your application to the Residency program.  While we are generally in favor of supporting research and development into account abstraction, we don't feel the Residency program is the best fit for this particular thread of research at this time.  However, we will be opening up a call for applications for Critical Bounties (RFP-style grants) that will include an open submission field (i.e. submit an idea of your choosing) and this could be an ideal mechanism for you to pursue this work.

Please follow our X account (https://twitter.com/StacksOrg) for updates and watch www.stacks.org/grants 

Best regard and apologies for the long response time.
Will
