### ISSUE TITLE
 "Project Exodus”: Democratizing London's Housing Market Through DAO and NFT Integration-in-Residence exploring Stacking-based business models"

### ISSUE THREAD

**Issue by mancub11** [stacksgov/residence-program#45]
**What's your name/your team's name?**
Jerelle from Value living Group

**Best email on which to contact you?**

jerellej@valueliving.com / jons@valueliving.com

**Personal Statement**
Project Exodus aims to revolutionize the London housing market by offering affordable living rents in prime locations. The project integrates NFTs to grant dividends from property rentals and allows fractional property ownership. This model enables broader community participation in property investment, fostering communal prosperity and sustainable urban living.

**End Product**
KYC on the blockchain useable by other DApps and DAO's

**Roadmap**
[Break your project down into a simple list of milestones and include the *approximate* dates by when you plan to complete them.]
Phase 1: Foundation and Strategic Planning

Market Analysis and Decentralization Pathway Development
Finalizing Property Portfolio
DAO Structure and Governance Model Establishment

Phase 2: Technology Development and Pilot Testing

Development of NFT Platform and Tokenization Model
Pilot Testing with Selected VLG Properties
Feedback Integration and System Refinement

Phase 3: Full-Scale DAO and NFT Implementation

Full-Scale Launch of DAO Operations
NFT Issuance and Distribution
Evaluation of Initial Performance and Investor Engagement

Phase 4: Expansion and Community Building

Expanding Property Portfolio within the DAO Framework
Enhancing Community Participation and Voting Mechanisms
Developing Additional Investor Outreach Programs

Phase 5: Consolidation and Long-Term Strategy

Assessing Market Position and Adjusting Strategy
Implementing Advanced Technology Features
Long-term Sustainability Planning and Investor Relations

**Appendix**
[Attach any supplemental materials such as previous work/accolades, notes, diagrams, preliminary research, or community interactions that could support your application.]

**Comment by will-corcoran** [comment]
Hi @mancub11 -

Thank you for your interest in the Stacks Residency program and for the time you invested in your application. We appreciate your patience as we completed our review process.

After thorough evaluation, we have concluded that the current focus of the Residency program, which emphasizes collaboration with the Stacks Core Engineering Working Group by subject matter experts, may not align closely with the nature of your proposed work. The program is specifically tailored to support individuals who are deeply involved in the core technical development of the Stacks ecosystem.

For insights into the specific goals and ongoing projects of the Stacks Core Engineering teams, we encourage you to join our [discussion board](https://github.com/orgs/stacks-network/discussions). This platform will provide you with a clearer understanding of our current needs and focus areas. We hope this will assist you in refining your proposal to better align with these objectives, and we welcome you to reapply in the future.

Thank you once again for your interest in contributing to the Stacks ecosystem. We wish you the best in your future endeavors.

Warm regards,

Will Corcoran
Ecosystem Program Manager
