### ISSUE TITLE
One line describing your role and work as a Resident, e.g. "Founder-of -Drooid  building  decentralized   swarm drones for critical missions in tight spaces that larger drones cannot access. "

### ISSUE THREAD

**Issue by Humancyyborg** [stacksgov/residence-program#46]
**What's your name/your team's name?** DROOID 

**Best email on which to contact you?** dankalu.work@gmail.com

**Personal Statement**
[Explain in 150 words or less the kind of work you'd like to do and why you think it could advance the ecosystem.]
Micro-drones present immense opportunities for critical search, surveillance, and defense operations in tight spaces that larger drones cannot access. 
Small bug drones equipped with sensors, imaging capabilities, navigation systems, and potentially small payloads offer mobility, maneuverability, and access to areas larger systems may not. This agility will aid disaster response teams, infrastructure inspectors, and military and security personnel in assessing better situations, threats, damages, and plan responses while reducing risks to human operators. However, significant technological barriers remain in bug-sized drones' navigation, coordination and functionality before this potential can be realized. At the [Drooid](https://drooid.xyz/), We're building decentralized swarm drones for critical missions in tight spaces that larger drones cannot access. Our drone swarms use blockchain technology for peer-to-peer command synchronization, information sharing, and collective decision-making without dependence on centralized servers. We selected Stack as an ideal decentralized framework to underpin trusted transactions and information sharing between the autonomous agents in our scalable drone swarms. Specifically, Stacks's configurable liquidity pools will enable us to create customized marketplaces for efficient data exchange, processing cycles, and additive manufacturing capacity across aerial robot fleets. We aim to build an open yet securely governed data coordination architecture for next-generation swarms enabled by the programmability and accessibility of the cutting-edge Stack protocol.

**End Product**
[Describe in 150 words or less the what you plan to contribute to the community by the end of your residency, e.g. a whitepaper or a series of developer tools.]

Our proposed project for the next 4-5 months involves allocating $20k for tooling and software to build out our physical prototype.

**Roadmap**
[Break your project down into a simple list of milestones and include the *approximate* dates by when you plan to complete them.]
--A refined version of our technical  whitepaper - December 31, 2023
-simulation of the prototype with bug algorithms - January 14th, 2024
-integrate decentralized decision-making algorithms - 24th,2024
-Build out a ten swarm bug drones based on  the simulation -February 20th,2024
-conduct the initial test in a simulated environment - March 05, 2024
-Refine and optimize swarm intelligence algorithms -March 30th,2024

**Appendix**
[Attach any supplemental materials such as previous work/accolades, notes, diagrams, preliminary research, or community interactions that could support your application.]
Addtional link
Link  to full proposal:https://shorturl.at/ikptx
website:[ https://drooid.xyz/](https://drooid.xyz/)
twitter:https://twitter.com/drooidHq
Discord:[ https://discord.com/invite/AAXCmJk6Mt](https://discord.com/invite/AAXCmJk6Mt)
Deck:https://shorturl.at/eklUY
Project Bounty:[ https://shorturl.at/cehuS](https://shorturl.at/cehuS)

**Comment by will-corcoran** [comment]
Hi @Humancyyborg -

Thank you for your interest in the Stacks Residency program and for the time you invested in your application. We appreciate your patience as we completed our review process.

After thorough evaluation, we have concluded that the current focus of the Residency program, which emphasizes collaboration with the Stacks Core Engineering Working Group by subject matter experts, may not align closely with the nature of your proposed work. The program is specifically tailored to support individuals who are deeply involved in the core technical development of the Stacks ecosystem.

For insights into the specific goals and ongoing projects of the Stacks Core Engineering teams, we encourage you to join our [discussion board](https://github.com/orgs/stacks-network/discussions). This platform will provide you with a clearer understanding of our current needs and focus areas. We hope this will assist you in refining your proposal to better align with these objectives, and we welcome you to reapply in the future.

Thank you once again for your interest in contributing to the Stacks ecosystem. We wish you the best in your future endeavors.

Warm regards,

Will Corcoran
Ecosystem Program Manager
