### ISSUE TITLE
Aspiring entrepreneur interested in the data and analytics stack for Crypto

### ISSUE THREAD

**Issue by ukrizna** [stacksgov/residence-program#5]
**What's your name/your team's name?** Uday Krishna

**Best email on which to contact you?** ukrizna@umich.edu

**Personal Statement**
[Explain in 150 words or less the kind of work you'd like to do and why you think it could advance the ecosystem.]
I'd like to work on the data stack and analytics stack of the crypto ecosystem. As of now, it's being done in the context of datasets for large companies or analytics for trading/investing. I'm thinking about it more so in the context of consumer analytics, product analytics for startups to take data-driven decisions as well as for retail investors to take data-driven decisions. This is important because this will ensure an ecosystem where everyone has the tools and wherewithal to make an informed decision.  

**End Product**
[Describe in 150 words or less the what you plan to contribute to the community by the end of your residency, e.g. a whitepaper or a series of developer tools.]
I'd say a combination of all 3 would be idea - a) Whitepaper b) atleast 1 usable tool for consumers c) atleast 1 usable tool for developers/startups to use (could be an API too). 

**Roadmap**
[Break your project down into a simple list of milestones and include the *approximate* dates by when you plan to complete them.]
- Understanding/Working with few ecosystems.
- Identifying data needs/requirements.
- Working on a prototype to create a data ecosystem.

**Appendix**
[Attach any supplemental materials such as previous work/accolades, notes, diagrams, preliminary research, or community interactions that could support your application.]

**Comment by jennymith** [comment]
Hey Uday, thanks for applying to be Stacks Residents. The Foundation team is currently reviewing your application in more depth and will be getting back to you about next steps soon.

**Comment by jennymith** [comment]
Thanks for your response @ukrizna. As it stands, we don't think this project outline qualifies for a full-time residency. However, this has some potential to receive a Stacks Grant. If you are interested in pursuing this route, take a look at the [projects submitted here](https://github.com/stacksgov/Stacks-Grants/issues). You are also welcome to reach out to me directly to discuss the scope of a possible grant. Thanks again for your time!

**Comment by ukrizna** [comment]
Thanks Jenny - I'd love to be considered for stacks grant. Can I connect
with you some time this week?

Thanks,
Uday
734-383-8492
