### ISSUE TITLE
BUIDLer-in-Residence exploring Stacking-based financial platform for synthetic assets and derivatives

### ISSUE THREAD

**Issue by CxtProgrammer** [stacksgov/residence-program#50]
**What's your name/your team's name?**
E Finance.

**Best email on which to contact you?**
cxtprogrammer@gmail.com

**Personal Statement**
We are building a decentralized financial platform for synthetic assets and derivatives on Bitcoin Layer 2, based on the Stacks.
We strongly believe that narratives surrounding Bitcoin Layer 2 solutions and the Stacks have the potential to become a major trend in the upcoming bull market, and DeFi is the key.

**End Product**
Become the most user-friendly synthetic assets and derivatives financial platform on the Stacks.

**Roadmap**
- <Mint Engine, after Nakamoto release.>
- <Asset Exchange Pools, after Nakamoto release>
- <Derivatives Trading, after above>

**Appendix**
[Attach any supplemental materials such as previous work/accolades, notes, diagrams, preliminary research, or community interactions that could support your application.]
[E* Finance BP EN_2024.pdf](https://github.com/stacksgov/residence-program/files/13803772/E.Finance.BP.EN_2024.pdf)

**Comment by will-corcoran** [comment]
Hi @CxtProgrammer -

Thank you for your interest in the Stacks Residency program and for the time you invested in your application. We appreciate your patience as we completed our review process.

After thorough evaluation, we have concluded that the current focus of the Residency program, which emphasizes collaboration with the Stacks Core Engineering Working Group by subject matter experts, may not align closely with the nature of your proposed work. The program is specifically tailored to support individuals who are deeply involved in the core technical development of the Stacks ecosystem.

For insights into the specific goals and ongoing projects of the Stacks Core Engineering teams, we encourage you to join our [discussion board](https://github.com/orgs/stacks-network/discussions). This platform will provide you with a clearer understanding of our current needs and focus areas. We hope this will assist you in refining your proposal to better align with these objectives, and we welcome you to reapply in the future.

Thank you once again for your interest in contributing to the Stacks ecosystem. We wish you the best in your future endeavors.

Warm regards,

Will Corcoran
Ecosystem Program Manager
