### ISSUE TITLE
One line describing your role and work as a Resident, e.g. "Entrepreneur-in-Residence exploring Stacking-based business models"

### ISSUE THREAD

**Issue by juggernott** [stacksgov/residence-program#51]
**What's your name/your team's name?**
I'm Eric, representing Thunder Labs, building LendX.network, a lending platform for the BTC ecosystem.

**Best email on which to contact you?**
lendx.network@gmail.com

**Personal Statement**
We want to bring Defi to the Bitcoin ecosystem as we believe there is currently a lack of infrastructure in the space.

**End Product**
With LendX, our goal is to create the first working lending platform and stablecoin on the BTC ecosystem. Once this product is shipped, we would be keen to see what else is lacking in the space and that synergizes with other products we are working on and to keep building.

**Roadmap**
Jan 2024: Start/join Singapore chapter of Stacks community
Feb 2024: Complete fundraising for LendX.network
June 2024: Launch $X
Sep 2024: Ship $xBTC

**Comment by will-corcoran** [comment]
Hi @juggernott -

Thank you for your interest in the Stacks Residency program and for the time you invested in your application. We appreciate your patience as we completed our review process.

After thorough evaluation, we have concluded that the current focus of the Residency program, which emphasizes collaboration with the Stacks Core Engineering Working Group by subject matter experts, may not align closely with the nature of your proposed work. The program is specifically tailored to support individuals who are deeply involved in the core technical development of the Stacks ecosystem.

For insights into the specific goals and ongoing projects of the Stacks Core Engineering teams, we encourage you to join our [discussion board](https://github.com/orgs/stacks-network/discussions). This platform will provide you with a clearer understanding of our current needs and focus areas. We hope this will assist you in refining your proposal to better align with these objectives, and we welcome you to reapply in the future.

Thank you once again for your interest in contributing to the Stacks ecosystem. We wish you the best in your future endeavors.

Warm regards,

Will Corcoran
Ecosystem Program Manager
