### ISSUE TITLE
Resident Oracle to promote and support DeFi on Stacks

### ISSUE THREAD

**Issue by abwrld** [stacksgov/residence-program#53]
**What's your name/your team's name?**
Pyth Data Association

**Best email on which to contact you?**
business@pyth.network

**Personal Statement**
The Pyth Data Association is a Swiss association founded by Pyth Network participants to advance the development of the Pyth Network. Decentralized finance relies on high-fidelity, time-sensitive, real-world data, but has no way to access it. Pyth connects high-fidelity market data from the world’s largest professional traders and exchanges to any smart contract, anywhere, and gives DeFi on Stacks comprehensive access to the vast amount of hi-fi financial services data it needs to make smart contracts work smarter.

**End Product**
Pyth Network is the largest first-party financial oracle solution delivering real-time market data to ~50 blockchains, including Stacks, in a secure, transparent manner. Pyth supports ~400 real-time price feeds across major asset classes including digital assets, equities, ETFs, FX, and commodities.

The network comprises some of the world’s largest exchanges, market makers, and financial services providers contributing their proprietary price data on-chain for aggregation and distribution to smart contract applications. Thanks to Pyth's innovative pull oracle design, applications can effortlessly “pull” the latest Pyth price onto their native blockchain on demand.

In less than a year, the network secures $2.0B in total value. Pyth has facilitated over $100B in trading volume and serves over 270 on- and off-chain applications.

**Roadmap**
01. Development of Pyth’s integration on the network along with Hiro team
02. Co-Marketing and Promotion for Stacks and DeFi projects building on Stacks
03. Ongoing Maintenance and Support of the Stacks receiver contract, including launch of new price feeds, and other relevant features which may be required.

**Appendix**
https://x.com/PythNetwork/status/1735676117191663809?s=20
https://pyth.network/blog/pyth-price-feeds-launch-on-stacks
https://twitter.com/PythNetwork/status/1696296670542049392

**Comment by will-corcoran** [comment]
Hi @abwrld,

We were excited to receive Pyth's application for the Stacks Residency program, and we're thrilled to have Pyth supporting Stacks with real-world market data!

However, after careful consideration, we believe the Residency program's focus on subject matter experts working directly with the Stacks Core Eng Working Group might not be the best fit for your proposed work. The Residency is designed to support individuals who collaborate deeply on the core technical development of Stacks, while your proposal seems like it could be a great fit for a dedicated integration and maintenance project, or perhaps there's an opportunity to explore collaboration through an alternative mechanism.

To get a better understanding of your specific goals and needs, and to help us connect you with the right individuals in the Stacks ecosystem, we'd love to chat further. Please contact me at **will at stacks dot org** to arrange a time to chat.

We're confident that there's a fantastic opportunity for collaboration, and we're eager to explore it further with you.

Best regards,

Will Corcoran
Ecosystem Program Manager
