### ISSUE TITLE
One line describing your role and work as a Resident, e.g. "I am Kingryan the ceo of Kingryanfoundation "

### ISSUE THREAD

**Issue by Kingryanfoundation** [stacksgov/residence-program#58]
**What's your name/your team's name?*kingryanfoundation*

**Best email on which to contact you?*lordnft794@gmail.com*

**Personal Statement**
[Explain in 150 words or less the kind of work you'd like to do and why you think it could advance the ecosystem.] What we do 
1. We support the less privileged : here are some things we plan to help the less privileged with 

A. Provision of resources : under provision of resources are 
Tokens : since the foundation is a crypto foundation ,we want to provide tokens for the people we are bringing to the ecosystem .
Food: since we also want to help the motherless babies home and charity ,we want to make sure that food is ok for the children, we also want to reach out to old people to support them medically.
Laptops: we also want the get developers for the ecosystem, so we want to get laptops to help people know and practice programming and development.
Bootcamps/training: so we also want to organize bootcamp and training to make people know how the ecosystem works.  

**End Product**
[Describe in 150 words or less the what you plan to contribute to the community by the end of your residency, e.g. a whitepaper or a series of developer tools.] HOW WILL THIS HELP STACK 
You know In Africa they not a lot of people in the the ecosystem so by us supporting them with laptops ,food,token,clothes. And by us organizing boot camps it will help people know more about  crypto and when they know we get more developers,artists e.t.c . So the foundation help in the marketing part 

**Roadmap**
[Break your project down into a simple list of milestones and include the *approximate* dates by when you plan to complete them.]
- <Milestone 1>
Provisions of laptops,provision of food 
- <Milestone 2>
Provision of tokens,and boot camps 
- ...

**Appendix**
[Attach any supplemental materials such as previous work/accolades, notes, diagrams, preliminary research, or community interactions that could support your application.]![image](https://github.com/stacksgov/residence-program/assets/154477626/34f9e5eb-42bf-4b87-a600-ae4388a2934f)

**Comment by will-corcoran** [comment]
Hi @Kingryanfoundation -

Thank you for your interest in the Residency program, but the purpose of this program does not align with the goals you are pursuing - additionally, Stacks Foundation funding is set aside to support research and development into decentralized computing, cryptography, and other new and novel forms of computer science.  These funds are not to be used for material goods as described in your proposal above.

That said, we wish you the best of luck in your future endeavors and would encourage you visit the website below for a list of all Stacks-related community-building opportunities.  One of these programs might better align with your goals.

https://www.stacks.co/explore/ecosystem?category=All+Teams#community

Best,
Will
