### ISSUE TITLE
Fund Classy Savage; Legendary Hybrid ( Ai >< OG ) Art; NFTs, Coin, etc.

### ISSUE THREAD

**Issue by russellrope** [stacksgov/residence-program#61]
**What's your name/your team's name?**
Classy Savage

**Best email on which to contact you?**
connect@classysavageart.com

**Personal Statement**
[Explain in 150 words or less the kind of work you'd like to do and why you think it could advance the ecosystem.]
Raising funds for the evolution of Classy Savage; Legendary ( Ai >< OG ) Art; NFTs, Meme Coin, Maybe Games, etc.

I can help advance the ecosystem through marketing, ROI, and am open to your ideas.

**End Product**
[Describe in 150 words or less the what you plan to contribute to the community by the end of your residency, e.g. a whitepaper or a series of developer tools.]

**Roadmap**
[Break your project down into a simple list of milestones and include the *approximate* dates by when you plan to complete them.]
- https://russellrope.com/real-legaltrillog-revolution
- https://classysavage.com
- https://instagram.com/classysavage.art
- https://twitter.com/classysavageart

**Appendix**
[Attach any supplemental materials such as previous work/accolades, notes, diagrams, preliminary research, or community interactions that could support your application.]
https://opensea.io/russellropoe
https://opensea.io/collection/classysavageart

**Comment by will-corcoran** [comment]
Hi @russellrope 

Thank you very much for your application to the Residency program. After careful consideration and review, we don't feel the Residency program is the best fit for this particular thread of research at this time. However, we will be opening up a call for applications for Critical Bounties (RFP-style grants) that will include an open submission field (i.e. submit an idea of your choosing) and this could be an ideal mechanism for you to pursue this work.

Please follow our X account (https://twitter.com/StacksOrg) for updates and watch [www.stacks.org/grants](http://www.stacks.org/grants)

Additionally, I would encourage you to explore one other programs that might be better suited for supporting your pursuits:
https://www.btcstartuplab.com/

Best,
Will

**Comment by russellrope** [comment]
Appreciate the response.  When do you expect the call for applications?

Realest,
@RussellRope
