### ISSUE TITLE
Entrepreneur-in-Residence exploring Governance models

### ISSUE THREAD

**Issue by iamhappy2day** [stacksgov/residence-program#64]
**What's your name/your team's name?**
Hi, I’m Sergei from Protofire. At [Protofire](https://protofire.io/), we’ve collaborated with over 50 networks and 65 protocols, building a vast repository of experience and knowledge. We’re eager to share this expertise and contribute to the Stacks ecosystem. For instance, we developed Solhint (a Solidity linter) and integrated Safe multisig across 30+ chains.

Before joining Protofire, I worked in VC as a researcher and was a Solidity developer. I’m deeply passionate about governance and the tools surrounding it. I’m really excited about the work the Stacks team is doing and would love to contribute personally, while also bringing Protofire’s extensive experience to the Stacks community.

**Best email on which to contact you?**
siarhei.ravenka@protofire.io

**Personal Statement**
Personally, I could start with some research tasks to receive initial feedback from your side, or I could propose solutions if Stacks needs custom development from Protofire. This could include some of Protofire’s offerings like Safe implementation, CDP (Liquity fork), Uniswap integration, etc.

**End Product**
Personally I am interested in governance and voting. I could do research on this and compare different existing governance system, associated risks, governance attacks etc.  As a team we can propose different infrastructure solutions to Stacks to enhance it's ecosystem:
- Safe, Uniswap , BlockScout integration
- Chainlink compatible oracles
- Indexing and subgraphs solutions
- Staking module, CDP etc.

**Roadmap**
Depends on Stacks needs

**Appendix**
My LinkedIn profile:  https://www.linkedin.com/in/sergeirevenko/
Protofire website: https://protofire.io/
Protofire X: https://x.com/protofire
My telegram/email: @sergeirevenko , siarhei.ravenka@protofire.io

**Comment by will-corcoran** [comment]
Hi @iamhappy2day 

Thank you for your application to the Residency program and for your interest in contributing to the Stacks ecosystem. We apologize for the delayed response.

At this time, our Residency program is primarily focused on supporting Subject Matter Experts (SMEs) in blockchain development and testing. While your and Protofire's extensive experience in the blockchain space is impressive, we are not currently bringing on new Residents except for very specific situations aligned with our current focus.

We truly appreciate your enthusiasm for governance and the Stacks ecosystem. Your portfolio and Protofire's track record are certainly noteworthy. We would encourage you to keep an eye on www.stacks.co/jobs for any opportunities that might align with your professional expertise and goals. Additionally, you might find interesting projects through our DeGrants program ([www.degrants.xyz](http://www.degrants.xyz/)) that could benefit from your skills.

Thank you again for your interest in Stacks. We wish you the best in your future endeavors.
Best regards,
Will
