### ISSUE TITLE
Residence Application: Boom Crypto

### ISSUE THREAD

**Issue by dantrevino** [stacksgov/residence-program#8]
**What's your name/your team's name?**

Boom Crypto

**Best email on which to contact you?**

dantrevino@gmail.com

**Personal Statement**

The Boom team would like to use this time in the Residence Program to expand the use of the PoX protocol for varied community funding models, potentially in conjunction with AppChains.   As the first NFT platform on Stacks, we intend to see where these novel forms of community funding can intersect with NFTs to push the medium well beyond "JPEGs." Our work has historically supported developers and creatives to get their feet wet in the Stacks ecosystem, and we believe this focused time in the program will enable us to continue doing so in the context of PoX funding and app chains.  Subnets are an unspecified technology at this point in time, but if there is time, and they show promise when specified, we would include these as well.

**End Product**

By the end of the residency, Boom will make it possible for creators and developers to realize entirely new funding methods for their projects, through the PoX services and tools that we launch. For creators this will take on the form of "custom Boombox NFTs" that are both funding mechanisms to enable their craft, and access passes so their supporters can engage with them more deeply and unlock new content. For developers this will look like the advancement of open PoX APIs, smart contracts, and expanding the potential of app chains in their relationship to PoX funding models.

**Roadmap**

![image](https://user-images.githubusercontent.com/7738/135922736-74e49022-f603-4880-90dd-20f77c4c35cf.png)

**Appendix**

Dan and the Boom team have a history of developing on Stacks and supporting the community.

**Comment by DeceptionsInMind** [comment]
I love your work on Boom, particularly the ease of which it is to mint NFT's. As a creator in this space I love imagining what the future holds for NFT's secured by Bitcoin, and incorporating the nuances of Stacks. Speaking of which, what do you see are the unique potentials for NFT's on Stacks as opposed to other technologies?

**Comment by dantrevino** [comment]
> I love your work on Boom, particularly the ease of which it is to mint NFT's. As a creator in this space I love imagining what the future holds for NFT's secured by Bitcoin, and incorporating the nuances of Stacks. Speaking of which, what do you see are the unique potentials for NFT's on Stacks as opposed to other technologies?

Personally I like that NFTs in general bring so much programmability to the creative space.  Stacks, in particular brings us really good tools for privacy and true (technical) data-ownership, which is lacking in the NFT space in general.  I think, put together, there are limitless possibilities to extend the usefulness of NFTs, and we hope to explore some of these during the residency.

**Comment by Miahelloworld** [comment]
I support this team. We also need a c2c NFT marketplace, we need to sell, buy and rent game NFT on stacks.

**Comment by jennymith** [comment]
Hey Boom Team, thanks for applying to be Stacks Residents. Great to see all the support you're getting already! The Foundation team is currently reviewing your application in more depth and will be getting back to you about next steps soon.

**Comment by jennymith** [comment]
For all community members interested in keeping up with Boom's residency, check out their upcoming plans and follow this thread for weekly updates from @dantrevino  and @amrro themselves:

### Scope of Work

**Background** 

Boom is bringing new depth to the creator-to-supporter relationship through novel NFT utility and fundraising mechanics. From minting to collecting, we're pushing the boundaries of this decentralized artistic medium to ensure that all people, not just current crypto users, remain at the center of the next wave of innovation. All on the Stacks blockchain, secured by Bitcoin. 

**Project Overview** 
The next 4 quarters will be broken down as follows: 
- Q1. Foundation - Updates to contracts, standards, ui and Interface open source components.
- Q2. User Experience - Lean into sovereignty and Stacks options for true data ownership, user minting, community rewards 
- Q3. Innovation - Novel minting and interactive technologies 
- Q4. Evolution - Boom DAO, analytics, and beyond 


**Scope & Milestones (Q1 of 1 Year Grant)** 
[Product Development]
- SIP-009 & SIP-012 compliant smart contract development for Boom NFTs and Boomboxes 
- Refactor Boombox contracts to support custom options 
- Marketplace auctions - enable auction smart contracts 
- Boom API Nodes - infrastructure to enable redundancy and distribute load off of Hiro servers 
- Community & Standards 
- Semi-Fungible token standard - work on developing and aligning community around a standard 
- Public Office hours - further participation in community governance groups Stretch Goals 
- Off-chain Profile standards - work with the community to align around profile standards as interim functionality until profile updates are available.

**Comment by dantrevino** [comment]
Recent highlights going back a couple of weeks:
Operations updates:
- presentation for Bitcoin Innovation Virtual Summit
- accounting sucks

Boom updates:
- focus on building out wallet
- provide users better view of stacking status for stx
- updated ui
- fixed existing wallet/navigation issue for mobile 
- nft api testing

Next:
- align/simplify input updates to the wallet and nft transfer fields
- pfp options for profile image
- fee estimation
- stacking stats for citycoins

**Comment by dantrevino** [comment]
- release boombox 32
- release support for 8 new tokens
- support nfts with only a cid in the image field
- add support for animation_url in nfts

**Comment by dantrevino** [comment]
- taxes
- rewriting existing display routines for the wallet
- shared a screenshot of the wallet in an emulator publicly on twitter: [https://twitter.com/dantrevino/status/1517622864412700673](https://twitter.com/dantrevino/status/1517622864412700673)
- onboarded @pahodl who is going to help with Clarity contracts
-
